export const he = {
  appName: 'קורסים',
  admin: 'ניהול',
  superAdmin: 'ניהול מערכת',

  // auth
  login: 'התחברות',
  logout: 'התנתקות',
  email: 'אימייל',
  password: 'סיסמה',
  currentPassword: 'סיסמה נוכחית',
  newPassword: 'סיסמה חדשה',
  changePassword: 'החלפת סיסמה',
  mustChangePassword: 'יש להחליף את הסיסמה לפני שממשיכים',
  invalidCredentials: 'אימייל או סיסמה שגויים',
  accountSuspended: 'החשבון מושעה',
  tooManyAttempts: 'יותר מדי ניסיונות, נסו שוב בעוד רגע',
  deviceLimitReached: 'חריגה ממגבלת המכשירים',
  deviceLimitExplain: 'החשבון מחובר כבר במספר המכשירים המרבי. יש להתנתק מאחד המכשירים ולנסות שוב.',
  activeDevices: 'מכשירים מחוברים',
  evictedNotice: 'החשבון הופעל ממכשיר אחר',
  loggingIn: 'מתחבר...',

  // nav
  dashboard: 'לוח בקרה',
  courses: 'קורסים',
  students: 'תלמידים',
  sessions: 'חיבורים פעילים',
  settings: 'הגדרות',
  backToCourses: 'חזרה לקורסים',
  myCourses: 'הקורסים שלי',

  // common
  save: 'שמירה',
  cancel: 'ביטול',
  delete: 'מחיקה',
  create: 'יצירה',
  add: 'הוספה',
  edit: 'עריכה',
  close: 'סגירה',
  copy: 'העתקה',
  copied: 'הועתק!',
  loading: 'טוען...',
  none: 'אין',
  confirmDelete: 'למחוק? הפעולה אינה הפיכה.',
  error: 'שגיאה',
  saved: 'נשמר',

  // courses
  courseTitle: 'שם הקורס',
  courseDescription: 'תיאור',
  newCourse: 'קורס חדש',
  draft: 'טיוטה',
  published: 'מפורסם',
  publish: 'פרסום',
  unpublish: 'החזרה לטיוטה',
  modules: 'פרקים',
  newModule: 'פרק חדש',
  moduleTitle: 'שם הפרק',
  lessons: 'שיעורים',
  newLesson: 'שיעור חדש',
  lessonTitle: 'שם השיעור',
  lessonNotes: 'הערות לשיעור',
  noCourses: 'אין קורסים עדיין',
  noLessons: 'אין שיעורים בפרק זה',
  enrollments: 'רישומים',
  enrollStudent: 'רישום תלמיד לקורס',
  unenroll: 'הסרת רישום',
  lessonCount: 'שיעורים',

  // media
  video: 'וידאו',
  uploadVideo: 'העלאת וידאו',
  replaceVideo: 'החלפת וידאו',
  removeVideo: 'הסרת וידאו',
  uploading: 'מעלה...',
  uploadFailed: 'ההעלאה נכשלה',
  attachments: 'קבצים מצורפים',
  addAttachment: 'צירוף קובץ',
  noVideo: 'לא הועלה וידאו לשיעור זה',
  cloudinaryMissing: 'Cloudinary אינו מוגדר — הגדירו מפתחות ב-.env כדי להעלות מדיה',
  download: 'הורדה',

  // students
  newStudent: 'תלמיד חדש',
  role: 'תפקיד',
  student: 'תלמיד',
  instructor: 'מדריך',
  owner: 'בעלים',
  status: 'סטטוס',
  active: 'פעיל',
  suspended: 'מושעה',
  suspend: 'השעיה',
  activate: 'הפעלה',
  resetPassword: 'איפוס סיסמה',
  lastLogin: 'התחברות אחרונה',
  liveSessions: 'חיבורים חיים',
  viewSessions: 'צפייה בחיבורים',
  killSession: 'ניתוק',
  emailTaken: 'האימייל כבר רשום',
  enrolledCourses: 'קורסים רשומים',

  // invites
  invites: 'הזמנות',
  newInvite: 'הזמנה חדשה',
  inviteLink: 'קישור הזמנה',
  inviteLinkNote: 'הקישור מוצג פעם אחת בלבד — העתיקו ושלחו לתלמיד',
  inviteExpires: 'תוקף',
  inviteUsed: 'נוצל',
  inviteFor: 'מיועד ל',
  anyEmail: 'כל אימייל',
  acceptInviteTitle: 'הצטרפות לקורסים',
  invalidInvite: 'קישור ההזמנה אינו תקף או שפג תוקפו',
  createAccount: 'יצירת חשבון',
  accountCreated: 'החשבון נוצר! אפשר להתחבר',

  // sessions
  device: 'מכשיר',
  ipAddress: 'כתובת IP',
  connectedSince: 'מחובר מאז',
  lastSeen: 'נראה לאחרונה',
  whoIsWatching: 'מי מחובר עכשיו',
  noLiveSessions: 'אין חיבורים פעילים כרגע',

  // settings
  tenantName: 'שם בית הספר',
  sessionLimit: 'מגבלת מכשירים לתלמיד',
  evictionPolicy: 'מדיניות בחריגה מהמגבלה',
  policyBlock: 'חסימת התחברות חדשה',
  policyEvictOldest: 'ניתוק המכשיר הישן ביותר',

  // player
  progress: 'התקדמות',
  completed: 'הושלם',
  continueWatching: 'המשך צפייה',

  // marketing & landing pages
  marketing: 'שיווק ודף נחיתה',
  landingPage: 'דף נחיתה',
  landingPreview: 'תצוגה מקדימה',
  landingPublish: 'פרסום הדף',
  landingUnpublish: 'הסרה מפרסום',
  landingPublished: 'הדף פומבי',
  landingDraftBadge: 'לא פורסם',
  landingLink: 'קישור לדף הנחיתה',
  landingShareNote: 'שתפו את הקישור בכל מקום — הדף פתוח לכולם, ללא התחברות',
  headline: 'כותרת ראשית',
  subheadline: 'משפט משנה',
  aboutSchool: 'על בית הספר / המדריך',
  instructorName: 'שם המדריך',
  audienceTitle: 'למי הקורס מתאים',
  audienceItem: 'קהל יעד (למשל: יזמים בתחילת הדרך)',
  outcomesTitle: 'מה תלמדו',
  outcomeItem: 'תוצאה (למשל: לבנות תקציב חודשי)',
  benefitsTitle: 'למה ללמוד אצלנו',
  benefitTitle: 'כותרת יתרון',
  benefitBody: 'פירוט קצר',
  testimonialsTitle: 'מה אומרים הבוגרים',
  testimonialName: 'שם הממליץ',
  testimonialQuote: 'ציטוט ההמלצה',
  faqTitle: 'שאלות נפוצות',
  faqQ: 'שאלה',
  faqA: 'תשובה',
  priceText: 'מחיר (טקסט חופשי, למשל: 490 ₪)',
  ctaText: 'טקסט כפתור הרשמה',
  ctaLink: 'קישור הרשמה (וואטסאפ / טופס / סליקה)',
  contactPhone: 'טלפון ליצירת קשר',
  contactEmail: 'אימייל ליצירת קשר',
  accentTitle: 'צבע הדף',
  emojiTitle: 'אייקון הקורס',
  curriculum: 'תוכנית הלימודים',
  enrollNow: 'להרשמה',
  paymentLink: 'קישור לתשלום (דף סליקה)',
  paymentLinkHint: 'כשהקישור מוגדר — כפתור ההרשמה בדף הנחיתה יוביל ישירות לתשלום',
  payNow: 'לתשלום מאובטח',
  galleryTitle: 'הצצה מבפנים',
  gallerySection: 'גלריה — תמונות וסרטונים קצרים',
  addPhoto: 'הוספת תמונה',
  addVideo: 'הוספת סרטון',
  galleryCaption: 'כיתוב (לא חובה)',
  galleryHint: 'עד 8 פריטים. תמונות, סרטונים קצרים ותוצאות לפני/אחרי',
  galleryAfterCreate: 'העלאת גלריה אפשרית אחרי יצירת הקורס, בלשונית השיווק',
  addBeforeAfter: 'הוספת לפני/אחרי',
  beforeLabel: 'לפני',
  afterLabel: 'אחרי',
  beforeAfterHint: 'בחרו קודם את תמונת ה"לפני", ומיד אחריה את תמונת ה"אחרי"',

  // student reviews
  reviews: 'ביקורות תלמידים',
  reviewsTitle: 'מה אומרים תלמידים אמיתיים',
  writeReview: 'איך היה הקורס?',
  writeReviewHint: 'סיימתם את הקורס — נשמח לשמוע! הביקורת תוצג בדף הקורס לאחר אישור',
  reviewRating: 'דירוג',
  reviewText: 'הביקורת שלכם',
  reviewSubmit: 'שליחת ביקורת',
  reviewThanks: 'תודה! הביקורת נשלחה ותוצג לאחר אישור',
  reviewApprove: 'אישור והצגה',
  reviewHide: 'הסתרה',
  reviewPending: 'ממתינה לאישור',
  reviewApproved: 'מוצגת בדף',
  noReviews: 'אין ביקורות עדיין',
  verifiedStudent: 'תלמיד/ה מאומת/ת',
  reviewPrivateNote: 'הערה למדריך (לא תפורסם)',
  reviewPrivateNoteHint: 'משוב אישי, בקשות או הצעות — יגיע רק למנהל הקורס',
  reviewEdit: 'עריכת הביקורת',
  reviewEditNote: 'אפשר לתקן ניסוח לפני הפרסום — הגרסה הערוכה תוצג בדף הנחיתה',
  privateNoteBadge: 'הערה פרטית',

  // course catalog (buy more courses)
  moreCourses: 'קורסים נוספים בבית הספר',
  moreCoursesHint: 'קורסים שאפשר להצטרף אליהם עכשיו',
  viewCourse: 'לפרטים והרשמה',

  // affiliates
  affiliateTitle: 'שתפו את הקורס וצברו מטבעות 🪙',
  affiliateHint: 'שתפו את הקישור האישי שלכם — כל {n} מבקרים ייחודיים בדף הקורס מזכים אתכם במטבע',
  affiliateYourLink: 'הקישור האישי שלכם',
  affiliateVisits: 'מבקרים ייחודיים',
  affiliateCoins: 'מטבעות שנצברו',
  affiliateToNext: 'עוד {n} מבקרים למטבע הבא',
  affiliateGetLink: 'קבלת קישור שיתוף',
  affiliatesSection: 'שיווק שותפים',
  affiliatesEmpty: 'עדיין אין שותפים — תלמידים שרכשו את הקורס יכולים לשתף קישור אישי ולצבור מטבעות',

  // course completion summary
  courseCompletedTitle: 'כל הכבוד, סיימתם את הקורס! 🎓',
  courseCompletedSub: 'הנה סיכום קצר של הדרך שעברתם',
  whatWeLearned: 'מה למדנו בקורס',
  summaryLessons: 'שיעורים',
  addItem: 'הוספת פריט',
  removeItem: 'הסרה',

  // onboarding wizard
  newCourseWizard: 'קורס חדש',
  wizardKicker: 'אשף הקמת קורס',
  wizardIntro: 'כמה שאלות קצרות — ובסוף מחכה לכם גם דף נחיתה מוכן לשיווק',
  stepBasics: 'פרטי הקורס',
  stepAudience: 'קהל ותוצאות',
  stepBenefits: 'יתרונות',
  stepSocial: 'הוכחה חברתית',
  stepPricing: 'מחיר והרשמה',
  stepStyle: 'עיצוב הדף',
  next: 'הבא',
  back: 'חזרה',
  skip: 'דילוג',
  finish: 'סיום ויצירה',
  optionalStep: 'אפשר לדלג ולהשלים אחר כך',
  wizardDone: 'הקורס נוצר!',
  wizardDoneHint: 'אפשר לערוך את התוכן, להוסיף שיעורים ולפרסם את דף הנחיתה',
  goToCourse: 'לעריכת הקורס',

  // superadmin
  tenants: 'בתי ספר',
  newTenant: 'בית ספר חדש',
  tenantSlug: 'מזהה (slug)',
  ownerEmail: 'אימייל הבעלים',
  ownerPassword: 'סיסמת הבעלים',
  usersCount: 'משתמשים',
  coursesCount: 'קורסים',
  slugTaken: 'המזהה תפוס',
  openTenant: 'מעבר לבית הספר',
} as const;

export type HeKey = keyof typeof he;
