export const he = {
  appName: 'GeniriSchool',
  admin: 'ניהול',
  superAdmin: 'ניהול מערכת',
  platformTagline: 'המקום שבו הידע שלכם הופך לעסק',

  // auth
  login: 'כניסה',
  logout: 'התנתקות',
  email: 'אימייל',
  password: 'סיסמה',
  currentPassword: 'הסיסמה הנוכחית',
  newPassword: 'סיסמה חדשה',
  changePassword: 'החלפת סיסמה',
  changePasswordTitle: 'שינוי סיסמה',
  mustChangePassword: 'רגע לפני שנכנסים — בואו נבחר סיסמה חדשה משלכם',
  invalidCredentials: 'האימייל או הסיסמה לא מסתדרים. ננסה שוב?',
  accountSuspended: 'החשבון בהשעיה כרגע',
  tooManyAttempts: 'רגע, נשמנו קצת יותר מדי מהר. שנייה של אוויר וננסה שוב',
  deviceLimitReached: 'הגעתם למכסת המכשירים',
  deviceLimitExplain: 'החשבון כבר פתוח במספר המרבי של מכשירים. מתנתקים מאחד — וממשיכים כרגיל.',
  activeDevices: 'מכשירים מחוברים',
  evictedNotice: 'נכנסו לחשבון ממכשיר אחר',
  loggingIn: 'רגע, נכנסים...',
  loginWelcome: 'טוב לראות אתכם שוב',
  loginSubtitle: 'נכנסים, וממשיכים בדיוק מאיפה שעצרתם.',
  authPanelTitle: 'החשבון שלכם, המכשירים שלכם. של אף אחד אחר.',
  authPanelText: 'כל חשבון שמור מאחורי מכסת מכשירים חכמה — כדי שהתוכן שקניתם יישאר שלכם, ורק שלכם.',
  deviceLimitTitle: 'הגעתם למכסת המכשירים',
  deviceLimitBody: 'החשבון כבר פתוח במספר המרבי של מכשירים. כדי להיכנס מכאן, פשוט מתנתקים מאחד המכשירים שלמטה ומנסים שוב. אין לחץ — זה קורה לכולם.',
  devicesInUse: 'מכשירים בשימוש עכשיו',
  outOf: 'מתוך',
  retryAfterLogout: 'ניתקתי — יאללה, ננסה שוב',
  backToLogin: 'חזרה לכניסה',
  dontRecognizeHint: 'לא מזהים אחד מהמכשירים? כדאי להחליף סיסמה כבר עכשיו, ליתר ביטחון.',
  evictedBody: 'מישהו נכנס לחשבון ממכשיר חדש, אז המכשיר הזה נותק אוטומטית. אם זה הייתם אתם — פשוט נכנסים שוב וממשיכים.',
  passwordHint: 'לפחות 8 תווים',

  // password recovery (self-serve)
  forgotLink: 'שכחתם את הסיסמה?',
  forgotTitle: 'נחזיר לכם את הגישה',
  forgotSubtitle: 'נשלח קישור למייל, ותבחרו סיסמה חדשה משלכם',
  forgotEmailHint: 'האימייל שאיתו נרשמתם',
  forgotSubmit: 'שליחת קישור לאיפוס',
  forgotSending: 'שולחים...',
  forgotSentTitle: 'הקישור בדרך אליכם',
  forgotSentBody:
    'שלחנו לאימייל קישור לבחירת סיסמה חדשה. הקישור בתוקף לשעה. שווה להציץ גם בתיקיית הספאם.',
  // plan webhook (package payments via Grow, incl. standing-order cycles)
  notifPlanActivatedTitle: 'חבילת {plan} הופעלה 🎉',
  notifPlanActivatedBody: 'התשלום התקבל והחבילה פעילה. אפשר לצרף תלמידים ולפרסם דפי מכירה.',
  mailPlanActivatedSubject: 'החבילה שלכם ב-GeniriSchool הופעלה — {plan}',
  mailPlanActivatedBody:
    'שלום,\n\nהתשלום התקבל וחבילת {plan} של בית הספר "{school}" פעילה.\nמכאן אפשר לצרף תלמידים, לפרסם דפי מכירה ולהתחיל למכור.\n\nפרטי החבילה: {link}\n\nצוות GeniriSchool',
  planWebhookAdminOk: '💰 תשלום חבילה: {school} — {plan} · {amount}₪ · תשלום מס׳ {count}',
  planWebhookAdminUnmatched:
    '⚠️ תשלום חבילה שלא זוהה: {email} · {amount}₪ — טפלו ידנית בעמוד החבילות',

  forgotNotFoundTitle: 'האימייל לא נמצא בבית הספר הזה',
  forgotNotFoundBody:
    'לא מצאנו חשבון עם הכתובת הזו כאן. בדקו שאין טעות הקלדה — או שאולי נרשמתם עם אימייל אחר. אם אתם בטוחים בכתובת, פנו למנהל בית הספר.',
  resetTitle: 'בוחרים סיסמה חדשה',
  resetSubtitle: 'עוד רגע אחד וחוזרים ללמוד',
  resetConfirmLabel: 'שוב, ליתר ביטחון',
  resetSubmit: 'שמירת הסיסמה',
  resetSaving: 'שומרים...',
  resetMismatch: 'שתי הסיסמאות לא זהות. ננסה שוב?',
  resetDoneTitle: 'הסיסמה הוחלפה ✓',
  resetDoneBody: 'אפשר להיכנס עכשיו עם הסיסמה החדשה. לכל שאר המכשירים נצטרך להיכנס מחדש.',
  resetInvalidTitle: 'הקישור כבר לא בתוקף',
  resetInvalidBody:
    'קישורי איפוס תקפים לשעה אחת ולשימוש אחד בלבד. אפשר לבקש קישור חדש — לוקח שנייה.',

  // platform support contact (one number for the whole platform)
  supportPhone: '053-289-8849',
  supportPhoneIntl: '972532898849',
  supportLine: 'צריכים עזרה? אנחנו כאן בוואטסאפ: {phone}',
  /** post-purchase message: platform tech support vs. the school's own content support */
  supportTechLine: 'תמיכה טכנית (כניסה, נגן, מכשירים) בוואטסאפ: {phone}',
  supportContentLine: 'שאלות על תוכן הקורס — לוואטסאפ של בית הספר: {phone}',

  // nav
  dashboard: 'לוח הבקרה',
  courses: 'קורסים',
  students: 'תלמידים',
  sessions: 'מחוברים עכשיו',
  settings: 'הגדרות',
  backToCourses: 'חזרה לקורסים',
  myCourses: 'הקורסים שלי',
  navMain: 'ראשי',
  logoAria: 'לוגו GeniriSchool',

  // common
  save: 'שמירה',
  cancel: 'ביטול',
  delete: 'מחיקה',
  create: 'יצירה',
  add: 'הוספה',
  edit: 'עריכה',
  close: 'סגירה',
  copy: 'העתקה',
  copied: 'הועתק',
  loading: 'רגע...',
  none: 'אין',
  optional: '(לא חובה)',
  unsavedChanges: 'יש כאן שינויים שעוד לא שמרתם',
  noStudentsYet: 'עוד אין תלמידים — אבל הם בדרך',
  noEnrollmentsYet: 'עוד אין רישומים לקורס הזה',
  noTenantsYet: 'עוד אין בתי ספר',
  noAffiliatesYet: 'עוד אין שגרירים',
  confirmDelete: 'למחוק לגמרי? אין דרך חזרה מכאן.',
  error: 'משהו השתבש',
  saved: 'נשמר ✓',
  loadFailed: 'הטעינה נכשלה. אפשר לרענן את הדף ולנסות שוב',

  // courses
  courseTitle: 'שם הקורס',
  courseDescription: 'תיאור',
  newCourse: 'קורס חדש',
  draft: 'טיוטה',
  published: 'באוויר',
  publish: 'פרסום',
  unpublish: 'החזרה לטיוטה',
  modules: 'פרקים',
  moduleOrdinal: 'פרק',
  newModule: 'פרק חדש',
  moduleTitle: 'שם הפרק',
  lessons: 'שיעורים',
  newLesson: 'שיעור חדש',
  lessonTitle: 'שם השיעור',
  lessonNotes: 'הערות לשיעור',
  noCourses: 'עוד אין כאן קורסים',
  noModules: 'עוד אין כאן פרקים',
  noLessons: 'הפרק הזה עוד מחכה לשיעורים',
  modulesEmptyHint: 'מתחילים מפרק אחד — ומוסיפים אליו שיעורים אחד־אחד',
  moveUp: 'הזזה למעלה',
  moveDown: 'הזזה למטה',
  dripAdvancedToggle: 'שחרור מדורג (מתקדם)',
  bulkAddLessons: 'הוספת כמה שיעורים בבת אחת',
  bulkAddLessonsHint: 'שם שיעור אחד בכל שורה',
  bulkAddLessonsPlaceholder: 'שיעור 1\nשיעור 2\nשיעור 3',
  bulkAddLessonsSubmit: 'הוספת השיעורים',
  bulkAddLessonsToggle: 'הוספה מרובה',
  enrollments: 'רישומים',
  enrollStudent: 'רישום תלמיד לקורס',
  unenroll: 'הסרת רישום',
  lessonCount: 'שיעורים',
  enrollmentsEmptyHint: 'כל תלמיד שיירשם לקורס יופיע כאן',
  courseTitlePlaceholder: 'למשל: שיווק דיגיטלי למתחילים',
  courseTitleHint: 'ככה התלמידים יראו את הקורס בתוך המערכת',

  // media
  video: 'וידאו',
  uploadVideo: 'העלאת וידאו',
  replaceVideo: 'החלפת הווידאו',
  removeVideo: 'הסרת הווידאו',
  uploading: 'מעלה...',
  uploadFailed: 'ההעלאה לא הצליחה. ננסה שוב?',
  uploadTooLarge: 'הקובץ גדול מדי — אפשר להעלות עד {size}. כדאי לדחוס אותו ולנסות שוב',
  uploadTooLargeUnknown: 'הקובץ גדול מדי להעלאה. כדאי לדחוס אותו ולנסות שוב',
  uploadNetworkError: 'ההעלאה נקטעה באמצע — בדקו את החיבור לאינטרנט ונסו שוב',
  attachments: 'קבצים מצורפים',
  addAttachment: 'צירוף קובץ',
  noVideo: 'עוד לא העליתם וידאו לשיעור הזה',
  cloudinaryMissing: 'העלאת מדיה עוד לא זמינה במערכת הזו — פנו למנהל הפלטפורמה כדי להפעיל אותה',
  download: 'הורדה',

  // students
  newStudent: 'תלמיד חדש',
  role: 'תפקיד',
  student: 'תלמיד',
  instructor: 'מדריך',
  owner: 'בעלים',
  status: 'סטטוס',
  active: 'פעיל',
  suspended: 'מושעה',
  suspend: 'השעיה',
  activate: 'הפעלה',
  name: 'שם',
  nameInviteHint: 'שם (יוצג בלוח התוצאות ובתעודות)',
  namePlaceholder: 'למשל: דנה כהן',
  anonymousLearner: 'תלמיד/ה',
  resetPassword: 'איפוס סיסמה',
  resetPasswordHint: 'התלמיד/ה ישתמשו בסיסמה הזו בכניסה הבאה',
  resetPasswordSuccess: 'הסיסמה אופסה ✓',
  lastLogin: 'כניסה אחרונה',
  liveSessions: 'מחוברים חיים',
  viewSessions: 'צפייה במחוברים',
  killSession: 'ניתוק',
  confirmKillSession: 'לנתק את המכשיר הזה? התלמיד/ה יתנתקו מיד ויצטרכו להתחבר מחדש.',
  emailTaken: 'האימייל הזה כבר רשום אצלנו',
  enrolledCourses: 'קורסים רשומים',
  studentsEmptyHint: 'מוסיפים תלמיד ראשון, או שולחים לו קישור הזמנה — והוא בפנים',
  newStudentPasswordHint: 'בכניסה הראשונה נבקש מהתלמיד לבחור סיסמה משלו',
  studentsSubtitle: 'החשבונות, ההזמנות והחיבורים של כל התלמידים — במקום אחד',
  deviceUnknown: 'מכשיר לא מזוהה',

  // invites
  invites: 'הזמנות',
  newInvite: 'הזמנה חדשה',
  inviteLink: 'קישור ההזמנה',
  inviteLinkNote: 'הקישור מופיע פעם אחת בלבד — מעתיקים ושולחים לתלמיד עכשיו',
  inviteExpires: 'בתוקף עד',
  inviteUsed: 'נוצל',
  inviteFor: 'מיועד ל',
  anyEmail: 'כל אימייל',
  acceptInviteTitle: 'רגע אחד — והחשבון שלכם מוכן',
  invalidInvite: 'הקישור הזה כבר לא תקף, או שפג תוקפו',
  createAccount: 'יאללה, פותחים חשבון',
  accountCreated: 'החשבון מוכן! נכנסים ומתחילים',
  inviteePanelTitle: 'הוזמנתם ללמוד איתנו',
  inviteePanelText: 'דקה של הרשמה — וכל הקורסים, השיעורים והחומרים כבר מחכים לכם בפנים.',

  // sessions
  device: 'מכשיר',
  ipAddress: 'כתובת IP',
  connectedSince: 'מחובר מאז',
  lastSeen: 'נראה לאחרונה',
  whoIsWatching: 'מי מחובר עכשיו',
  noLiveSessions: 'כרגע אף אחד לא מחובר',
  noLiveSessionsHint: 'ברגע שתלמיד ייכנס לצפות, הוא יופיע כאן בזמן אמת.',
  liveUpdate: 'מתעדכן חי',
  sessionsSummary: '{n} מחוברים פעילים אצל {m} תלמידים',
  policyPrefix: 'המדיניות:',
  upToDevices: 'עד {n} מכשירים לכל תלמיד/ה',
  searchByEmail: 'חיפוש לפי אימייל…',
  atLimitBadge: 'הגיע למכסה',
  multiIpWarning: 'כמה כתובות IP שונות באותו הרגע — יכול להיות שהחשבון משותף. שווה לבדוק.',
  refreshedPrefix: 'עודכן',

  // settings
  tenantName: 'שם בית הספר',
  sessionLimit: 'מכסת מכשירים לתלמיד',
  sessionLimitSubtitle: 'כמה מכשירים יכולים להיות מחוברים בו־זמנית לאותו חשבון',
  evictionPolicy: 'מה קורה כשעוברים את המכסה',
  policyBlock: 'חוסמים כניסה חדשה',
  policyBlockHint: 'מכשיר נוסף מעבר למכסה פשוט לא ייכנס — עד שאחד הקיימים יתנתק',
  policyEvictOldest: 'מנתקים את הישן ביותר',
  policyEvictOldestHint: 'כניסה חדשה מנתקת אוטומטית את המכשיר הכי פחות פעיל',

  // player
  progress: 'התקדמות',
  completed: 'הושלם',
  continueWatching: 'ממשיכים לצפות',

  // course editor — hub + sub-hub tiles
  courseSectionContentDesc: 'ניהול פרקים, שיעורים וסדר ההופעה שלהם.',
  courseSectionStudentsDesc: 'הרשמה וביטול הרשמה של תלמידים לקורס.',
  courseSectionMarketingDesc: 'עמוד נחיתה, תמחור, ביקורות ושותפים.',
  marketingCopyLabel: 'טקסטים ותוכן',
  marketingCopyDesc: 'כותרת, קהל יעד, יתרונות, המלצות ושאלות נפוצות.',
  marketingGalleryLabel: 'גלריה ומדיה',
  marketingGalleryDesc: 'תמונות וסרטון תדמית שנוצר על ידי AI.',
  marketingReviewsDesc: 'אישור והצגת ביקורות תלמידים על הקורס.',
  marketingAffiliatesDesc: 'ניהול שותפים ועמלות הפצה.',
  marketingPromotionDesc: 'מבצע זמני או חבילה משולבת עם קורס אחר.',
  marketingPublishLabel: 'פרסום ושיתוף',
  marketingPublishDesc: 'כתובת העמוד, פרסום או הסרה, ופרטי יצירת קשר.',
  marketingStyleLabel: 'עיצוב הדף',
  marketingStyleDesc: 'פריסה, צבע מבטא ואייקון לדף הנחיתה.',

  // homepage builder — hub tiles
  homepageSectionWelcomeDesc: 'כותרת פתיחה וטקסט אודות בית הספר.',
  homepageSectionAnnouncementsDesc: 'ניהול רשימת הודעות ועדכונים לתלמידים.',
  homepageSectionSectionsDesc: 'הצגת סטטיסטיקות, הישגים, קטלוג וקורס מומלץ.',
  homepageSectionStyleDesc: 'צבע מבטא ואייקון לעמוד הבית.',

  // marketing & landing pages
  marketing: 'שיווק ודף נחיתה',
  landingPage: 'דף נחיתה',
  landingPreview: 'הצצה מקדימה',
  landingPublish: 'פרסום הדף',
  landingUnpublish: 'הורדה מפרסום',
  landingPublished: 'הדף באוויר',
  landingDraftBadge: 'עוד לא פורסם',
  landingLink: 'הקישור לדף הנחיתה',
  landingShareNote: 'שתפו את הקישור בכל מקום — הדף פתוח לכולם, בלי צורך להתחבר',
  aiMediaTitle: 'סרטון שיווקי ב-AI',
  aiMediaHint: 'נייצר לכם סרטון קולנועי בהתאמה אישית לקורס — הוא ייפתח את דף הנחיתה באנימציית גלילה שקשה להתעלם ממנה',
  aiMediaGenerate: 'יאללה, מייצרים סרטון',
  aiMediaRegenerate: 'ליצירה מחדש',
  aiMediaGenerating: 'מייצרים לכם סרטון בהתאמה אישית… זה לוקח כמה דקות, שווה לחכות',
  aiMediaReady: 'הסרטון מוכן ומככב בדף הנחיתה',
  aiMediaFailed: 'יצירת הסרטון לא הצליחה הפעם. ננסה שוב?',
  aiMediaDisabled: 'יצירת מדיה ב-AI לא מופעלת בשרת הזה',
  aiMediaVideoDisabled: 'יצירת סרטון AI מושהית זמנית (עלות גבוהה) — פנו למנהל המערכת',
  aiMediaCloudinaryMissing: 'כדי לשמור את הסרטון צריך להגדיר קודם את Cloudinary',
  headline: 'הכותרת הגדולה',
  headlineSubtitle: 'המשפט הראשון שמקבל את הפנים של המבקרים',
  headlineHint: 'הכותרת הכי גדולה בדף — אם משאירים ריק, נשתמש בשם הקורס',
  subheadline: 'משפט המשך',
  subheadlinePlaceholder: 'משפט אחד שגורם למבקר להבין: זה בדיוק בשבילי',
  aboutSchool: 'על בית הספר / המדריך',
  aboutSchoolPlaceholder: 'כמה מילים עליכם — מי אתם, מאיפה הגעתם, ולמה שווה ללמוד דווקא אצלכם',
  storyTitle: 'סקשנים נוספים בדף',
  storySubtitle: 'כל סקשן מופיע בנפרד בדף הנחיתה, מתחת לפסקת הפתיחה',
  storySectionTitle: 'כותרת הסקשן (למשל: למה יצרתי את הקורס?)',
  storySectionBody: 'תוכן הסקשן',
  instructorName: 'שם המדריך',
  withInstructor: 'עם',
  audienceTitle: 'למי זה מדבר',
  audienceItem: 'קהל יעד (למשל: יזמים בתחילת הדרך)',
  outcomesTitle: 'מה תדעו לעשות בסוף',
  outcomeItem: 'תוצאה (למשל: לבנות תקציב חודשי שבאמת מחזיק)',
  benefitsTitle: 'למה דווקא אצלנו',
  benefitTitle: 'כותרת היתרון',
  benefitBody: 'עוד משפט קצר',
  testimonialsTitle: 'מה אומרים הבוגרים',
  testimonialName: 'שם הממליץ',
  testimonialQuote: 'מה שכתבו',
  faqTitle: 'שאלות ששואלים אותנו',
  faqQ: 'שאלה',
  faqA: 'תשובה',
  priceText: 'מחיר (טקסט חופשי, למשל: 490 ₪)',
  ctaText: 'הטקסט על כפתור ההרשמה',
  ctaLink: 'קישור להרשמה (וואטסאפ / טופס / סליקה)',
  ctaLinkSubtitle: 'לאן הכפתור הגדול לוקח את המבקר',
  ctaLinkHint: 'קישור חלופי כשאין דף תשלום — וואטסאפ או טופס הרשמה',
  contactPhone: 'טלפון ליצירת קשר',
  contactEmail: 'אימייל ליצירת קשר',
  accentTitle: 'צבע הדף',
  emojiTitle: 'האייקון של הקורס',
  layoutTitle: 'סגנון דף הנחיתה',
  layoutClassic: 'קלאסי',
  layoutClassicHint: 'הסגנון המקורי של GeniriSchool — עדין ורב-שימושי',
  layoutCoralHota: 'קורל הוטה',
  layoutCoralHotaHint: 'סגנון בוטיק חם: קרם ושחור, כותרת בכתב־יד וכפתורים עגולים',
  whatsIncludedTitle: 'מה כלול בקורס',
  footerQuickLinks: 'ניווט מהיר',
  footerContact: 'יצירת קשר',
  scrollToTop: 'חזרה למעלה',
  curriculum: 'מה לומדים בפנים',
  enrollNow: 'יאללה, מתחילים',
  digitalCourseBadge: 'קורס דיגיטלי',
  hoursVideo: 'שעות וידאו',
  yourInstructor: 'המנחה שלכם',
  ctaCoinsNote: '🪙 משתפים את הקורס אחרי שקניתם — וצוברים מטבעות',
  ctaAccessNote: 'גישה מיידית לכל השיעורים, לכל החיים. צופים מכל מכשיר — עד {n} במקביל.',
  paymentLink: 'קישור לתשלום (דף סליקה)',
  paymentLinkHint: 'ברגע שיש קישור — כפתור ההרשמה בדף יוביל ישר לתשלום',
  payNow: 'לתשלום מאובטח',

  // Checkout — the form we collect before handing the buyer to Hyp's page.
  checkoutTitle: 'סיום רכישה',
  checkoutSubtitle: 'עוד רגע קטן והקורס שלכם. נשלח את פרטי הכניסה לוואטסאפ ולמייל מיד אחרי התשלום.',
  checkoutIncludes: 'הרכישה כוללת',
  checkoutAddonsTitle: 'רוצים להוסיף?',
  checkoutAddonPlus: '+{price}',
  checkoutTotal: 'סה"כ לתשלום',
  checkoutName: 'שם מלא',
  checkoutEmail: 'דוא"ל',
  checkoutEmailHint: 'לכאן יגיעו פרטי הכניסה — בדקו שאין טעות',
  checkoutPhone: 'טלפון נייד',
  checkoutPhoneHint: 'לוואטסאפ עם שם המשתמש והסיסמה',
  checkoutPay: 'מעבר לתשלום מאובטח',
  checkoutSubmitting: 'מעבירים אתכם לתשלום…',
  checkoutSecureNote: '🔒 התשלום מתבצע בדף מאובטח של Hyp. פרטי האשראי לא עוברים דרכנו ולא נשמרים אצלנו.',
  checkoutBackToCourse: 'חזרה לדף הקורס',
  checkoutError: 'משהו השתבש בדרך לתשלום. נסו שוב עוד רגע, ואם זה חוזר — דברו איתנו.',
  checkoutErrorNoPrice: 'הקורס הזה עדיין לא פתוח לרכישה. דברו איתנו ונסדר.',
  checkoutErrorStale: 'ההצעה התעדכנה בינתיים. רעננו את הדף ונסו שוב.',

  // Payment failure landing (Hyp redirects here when the charge did not go through)
  payFailedTitle: 'התשלום לא הושלם',
  payFailedBody: 'לא חויבתם. זה קורה לפעמים — כרטיס שנדחה, חיבור שנפל, או סתם דף שנסגר באמצע.',
  payFailedRetry: 'לנסות שוב',
  payFailedSupport: 'אם ירדו לכם כספים או שזה חוזר — כתבו לנו ונטפל בזה מיד.',
  payFailedBackHome: 'חזרה לדף הבית',

  thankYouTitle: 'הרכישה התקבלה',
  thankYouBody: 'שלחנו לכם הודעה עם פרטי הכניסה לקורס "{course}" — לדוא"ל ולוואטסאפ. בדקו את תיבת הדואר הנכנס (וגם את הספאם) כדי להתחבר.',
  thankYouHint: 'ההודעה יכולה לקחת כמה דקות להגיע.',
  thankYouLoginButton: 'כניסה למערכת',
  thankYouBackToCourse: 'חזרה לדף הקורס',
  resultsTitle: 'התוצאות מדברות בעד עצמן',
  resultsSubtitle: 'תמונות של מה שהתלמידים שלנו הוציאו מהתנור',
  resultsNav: 'התוצאות',
  resultsSection: 'התוצאות מדברות בעד עצמן',
  resultsHint: 'עד 12 תמונות. אפשר לבחור כמה תמונות יחד — הן יוצגו בגלריה בדף הנחיתה',
  resultsAddPhotos: 'הוספת תמונות',
  resultsEmpty: 'עדיין לא הועלו תמונות',
  resultsUploadingCount: 'מעלה תמונה {i} מתוך {n}',
  resultsOpen: 'הגדלת התמונה',
  resultsClose: 'סגירה',
  resultsPrev: 'התמונה הקודמת',
  resultsNext: 'התמונה הבאה',
  galleryTitle: 'הצצה מבפנים',
  gallerySection: 'גלריה — תמונות וסרטונים קצרים',
  addPhoto: 'הוספת תמונה',
  addVideo: 'הוספת סרטון',
  galleryCaption: 'כיתוב (לא חובה)',
  galleryHint: 'עד 8 פריטים. תמונות, קליפים קצרים ותוצאות של לפני/אחרי',
  galleryAfterCreate: 'את הגלריה אפשר להעלות אחרי שהקורס נוצר, בלשונית השיווק',
  addBeforeAfter: 'הוספת לפני/אחרי',
  beforeLabel: 'לפני',
  afterLabel: 'אחרי',
  beforeAfterHint: 'קודם בוחרים את תמונת ה"לפני", ומיד אחריה את ה"אחרי"',
  galleryBeforeDone: '✓ תמונת ה"לפני" עלתה — עכשיו בוחרים את תמונת ה"אחרי"',
  galleryPickAfter: 'בחירת תמונת ה"אחרי"',

  // landing sale / bundle offer
  saleSection: 'מבצע בדף הנחיתה',
  saleSectionHint: 'מחברים קורס נוסף ומציעים הטבה — למשל 1+1, או הנחה על הקורס השני',
  saleEnable: 'להציג את המבצע בדף הנחיתה',
  saleTitleLabel: 'כותרת המבצע',
  saleTitlePlaceholder: 'למשל: קונים קורס אחד — והשני עלינו!',
  saleDescriptionLabel: 'פרטי המבצע (טקסט חופשי)',
  salePartnerCourse: 'הקורס שמצטרף למבצע',
  salePartnerNone: 'בלי קורס מקושר',
  salePaymentLink: 'קישור לתשלום עבור המבצע',
  salePaymentLinkHint: 'דף סליקה ייעודי לעסקת המבצע — כפתור המבצע יוביל אליו',
  saleEndsAt: 'בתוקף עד (לא חובה)',
  saleEndsAtHint: 'אחרי התאריך הזה המבצע פשוט ייעלם מהדף לבד',
  saleBadge: 'מבצע מיוחד',
  saleEndsOn: 'המבצע בתוקף עד',
  saleCta: 'לתפוס את המבצע',
  saleIncludedCourse: 'הקורס שמצטרף למבצע',
  saleExpired: 'תאריך המבצע עבר — הוא מוסתר מהדף',
  saleEndsIn: 'המבצע נגמר בעוד',
  countdownDays: 'ימים',
  countdownHours: 'שעות',
  countdownMinutes: 'דקות',
  countdownSeconds: 'שניות',

  // landing conversion / trust
  trustInstantAccess: 'נכנסים מיד',
  trustLifetime: 'שלכם לכל החיים',
  trustAnyDevice: 'צופים מכל מכשיר',
  trustSecurePayment: 'תשלום מאובטח',
  studentsEnrolled: 'תלמידים כבר לומדים כאן',
  midCtaTitle: 'אז מה, נצא לדרך?',
  midCtaSubtitle: 'נרשמים עכשיו — וכל השיעורים נפתחים מיד, לכל החיים',
  limitedOffer: 'ההרשמה פתוחה עכשיו',
  landingHaveCode: 'יש לכם קוד גישה? למימוש הקוד',

  // student reviews
  reviews: 'ביקורות',
  reviewsTitle: 'מה אומרים תלמידים אמיתיים',
  writeReview: 'אז איך היה?',
  writeReviewHint: 'סיימתם את הקורס — נשמח לשמוע! הביקורת תופיע בדף הקורס אחרי אישור',
  reviewRating: 'דירוג',
  reviewText: 'הביקורת שלכם',
  reviewSubmit: 'שליחת הביקורת',
  reviewThanks: 'תודה רבה! שלחנו — והיא תופיע בדף אחרי אישור',
  reviewApprove: 'לאשר ולהציג',
  reviewHide: 'הסתרה',
  reviewPending: 'מחכה לאישור',
  reviewApproved: 'מופיעה בדף',
  noReviews: 'עוד אין ביקורות — אתם יכולים להיות הראשונים',
  reviewsEmptyHint: 'תלמידים שיסיימו את הקורס יתבקשו להשאיר ביקורת — והיא תגיע לכאן לאישור',
  verifiedStudent: 'תלמיד/ה מאומת/ת',
  reviewPrivateNote: 'משהו למדריך (לא יתפרסם)',
  reviewPrivateNoteHint: 'מחשבה אישית, בקשה או רעיון — יגיע רק למנהל הקורס',
  reviewEdit: 'עריכת הביקורת',
  reviewEditNote: 'אפשר ללטש את הניסוח לפני הפרסום — הגרסה הערוכה היא זו שתופיע בדף',
  privateNoteBadge: 'הערה פרטית',

  // course catalog (buy more courses)
  moreCourses: 'עוד קורסים אצלנו',
  moreCoursesHint: 'קורסים שאפשר להצטרף אליהם כבר עכשיו',
  viewCourse: 'לפרטים והרשמה',

  // affiliates
  affiliateTitle: 'שתפו את הקורס וצברו מטבעות 🪙',
  affiliateHint: 'שתפו את הקישור האישי שלכם — כל {n} מבקרים חדשים בדף הקורס מזכים אתכם במטבע',
  affiliateYourLink: 'הקישור האישי שלכם',
  affiliateVisits: 'מבקרים ייחודיים',
  affiliateCoins: 'מטבעות שצברתם',
  affiliateToNext: 'עוד {n} מבקרים למטבע הבא',
  affiliateGetLink: 'קבלת קישור לשיתוף',
  affiliateRefCode: 'קוד שיתוף',
  shareWhatsapp: 'שיתוף בוואטסאפ',
  shareInstagram: 'שיתוף בסטורי',
  shareGeneric: 'שיתוף...',
  shareText: 'שווה לכם להציץ בקורס שאני לומד/ת:',
  instagramCopied: 'העתקנו את הקישור! פותחים סטורי באינסטגרם ומדביקים אותו כסטיקר קישור (Link)',
  affiliatesSection: 'שיווק שותפים',
  affiliatesEmpty: 'עוד אין שותפים — כל תלמיד שקנה את הקורס יכול לשתף קישור אישי ולצבור מטבעות',

  // course completion summary
  courseCompletedTitle: 'סיימתם את הקורס',
  courseCompletedSub: 'הנה סיכום קטן של כל הדרך שעברתם',
  whatWeLearned: 'מה עברנו יחד',
  summaryLessons: 'שיעורים',
  addItem: 'הוספת פריט',
  removeItem: 'הסרה',

  // onboarding wizard
  newCourseWizard: 'קורס חדש',
  wizardKicker: 'בונים קורס',
  wizardIntro: 'כמה שאלות קצרות — ובסוף מחכה לכם קורס וגם דף נחיתה מוכן לשיווק',
  wizardStepsAria: 'שלבים',
  stepBasics: 'פרטי הקורס',
  stepAudience: 'קהל ותוצאות',
  stepBenefits: 'יתרונות',
  stepSocial: 'הוכחה חברתית',
  stepPricing: 'מחיר והרשמה',
  stepStyle: 'עיצוב הדף',
  next: 'הבא',
  back: 'חזרה',
  skip: 'דילוג',
  finish: 'יאללה, יוצרים',
  optionalStep: 'אפשר לדלג עכשיו ולהשלים אחר כך',
  wizardDone: 'הקורס מוכן',
  wizardDoneHint: 'עכשיו אפשר להוסיף שיעורים, לערוך תוכן ולפרסם את דף הנחיתה',
  goToCourse: 'לעריכת הקורס',

  // student home dashboard
  greetingMorning: 'בוקר טוב',
  greetingNoon: 'צהריים טובים',
  greetingEvening: 'ערב טוב',
  greetingNight: 'לילה טוב',
  homeSubtitle: 'ממשיכים מאיפה שעצרתם — ההתקדמות נשמרת לבד',
  noCoursesHint: 'עוד רגע מתמלא כאן — הקורס הראשון שלכם ממש מעבר לפינה',
  continueLearning: 'ממשיכים ללמוד',
  nextLessonLabel: 'השיעור הבא',
  allCaughtUp: 'סיימתם הכול. כל הכבוד',
  allCaughtUpHint: 'אולי זה הרגע להרפתקה חדשה? שווה להציץ בקטלוג הקורסים',
  streakDays: 'ימי רצף',
  statsStreak: 'רצף נוכחי',
  statsLessonsDone: 'שיעורים שסיימתם',
  statsCoursesDone: 'קורסים שסיימתם',
  statsMinutes: 'דקות של למידה',
  announcementsTitle: 'מה חדש',
  aboutSchoolTitle: 'על בית הספר',
  featuredCourse: 'הקורס המומלץ',

  // journey page
  journeyTitle: 'המסע שלי',
  journeySubtitle: 'ההתקדמות, הרצף וההישגים שלכם — הכול במקום אחד',
  activityLast4Weeks: 'הפעילות שלכם בארבעת השבועות האחרונים',
  activityDaysCount: 'ימי למידה בחודש האחרון',
  perCourseProgress: 'התקדמות לפי קורס',
  achievementsTitle: 'הישגים',
  achievementLocked: 'עוד לא נפתח',
  viewAllAchievements: 'לכל ההישגים',
  achievementsUnlocked: 'הישגים שפתחתם',
  achFirstLesson: 'הצעד הראשון',
  achFirstLessonDesc: 'סיימתם את השיעור הראשון',
  achLessons5: 'תופסים תאוצה',
  achLessons5Desc: '5 שיעורים מאחוריכם',
  achLessons10: 'ממריאים',
  achLessons10Desc: '10 שיעורים מאחוריכם',
  achLessons25: 'כובשים פסגות',
  achLessons25Desc: '25 שיעורים מאחוריכם',
  achFirstCourse: 'קו הסיום',
  achFirstCourseDesc: 'קורס ראשון הושלם מתחילתו ועד סופו',
  achCourses3: 'אספני ידע',
  achCourses3Desc: '3 קורסים הושלמו',
  achStreak3: 'על הגל',
  achStreak3Desc: '3 ימי למידה ברצף',
  achStreak7: 'שבוע מושלם',
  achStreak7Desc: '7 ימי למידה ברצף',

  // owner homepage builder
  homepageBuilder: 'עמוד הבית',
  homepageBuilderSubtitle: 'ככה ייראה עמוד הבית של התלמידים — עיצוב, הודעות ותוכן על בית הספר',
  homepageWelcome: 'ברכת פתיחה',
  homepageWelcomeHeadline: 'כותרת פתיחה (מופיעה ליד הברכה)',
  homepageWelcomeHeadlinePlaceholder: 'למשל: כיף שהגעתם לסטודיו!',
  homepageAboutSchool: 'על בית הספר',
  homepageAboutSchoolHint: 'כמה משפטים על בית הספר — התלמידים יראו אותם בעמוד הבית',
  homepageAnnouncements: 'הודעות ועדכונים',
  homepageAnnouncementsHint: 'עד 10 הודעות — החדשות למעלה. יופיעו בלוח המודעות של התלמידים',
  announcementTitle: 'כותרת ההודעה',
  announcementBody: 'תוכן ההודעה',
  announcementDate: 'תאריך',
  homepageSections: 'מה מציגים בעמוד',
  homepageShowStats: 'שורת הנתונים האישיים (שיעורים, רצף, דקות)',
  homepageShowAchievements: 'הישגים',
  homepageShowCatalog: 'קטלוג קורסים נוספים',
  homepageFeaturedCourse: 'קורס מודגש בקטלוג',
  homepageFeaturedNone: 'ללא',
  homepagePreview: 'הצצה מקדימה',
  homepageStyle: 'עיצוב עמוד הבית',

  // superadmin
  tenants: 'בתי ספר',
  newTenant: 'בית ספר חדש',
  tenantSlug: 'מזהה בית הספר בכתובת',
  tenantSlugHint: 'אותיות קטנות באנגלית ומקפים בלבד — זה מה שיופיע בכתובת',
  ownerEmail: 'אימייל הבעלים',
  ownerPassword: 'סיסמת הבעלים',
  ownerPasswordHint: 'בכניסה הראשונה נבקש מהבעלים לבחור סיסמה משלו',
  usersCount: 'משתמשים',
  coursesCount: 'קורסים',
  slugTaken: 'המזהה הזה כבר תפוס',
  openTenant: 'כניסה לבית הספר',
  tenantsEmptyHint: 'יאללה, מקימים את בית הספר הראשון בפלטפורמה',
  confirmSuspendTenant: 'להשעות את "{name}"? כל התלמידים והצוות לא יוכלו להיכנס עד שתבטלו את ההשעיה.',
  deleteTenantTitle: 'מחיקת בית ספר',
  deleteTenantWarning:
    'הפעולה תמחק לצמיתות את כל הקורסים, התלמידים והרכישות של בית הספר הזה. אין דרך לשחזר.',
  deleteTenantConfirmLabel: 'כדי לאשר, הקלידו את שם בית הספר',
  deleteTenantButton: 'מחיקה לצמיתות',
  tenantsSubtitle: 'כל בתי הספר בפלטפורמה — הקמה, השעיה ומחיקה',
  superAdminLoginSubtitle: 'הכניסה כאן שמורה למנהלי הפלטפורמה בלבד',
  superAdminPanelTitle: 'שליטה מלאה, מקצה לקצה',
  superAdminPanelText: 'מנהלים בתי ספר, השעיות ומעקב שימוש — מכל מקום, בראש שקט.',

  // owner admin dashboard
  adminOverviewTitle: 'מה קורה אצלכם היום',
  adminOverviewSubtitle: 'כל מה שצריך לניהול בית הספר שלכם — במקום אחד.',
  instructorOverviewTitle: 'מה קורה בקורסים שלכם',
  adminSessionsEmptyHint: 'ברגע שתלמיד ייכנס, החיבור החי יופיע כאן',
  adminInviteStudent: 'הזמנת תלמיד',
  adminStatScreensNow: 'מסכים פתוחים עכשיו',
  adminStatScreensSub: 'צפייה חיה ברגע זה',
  adminStatStudentsSub: 'רשומים בבית הספר',
  adminStatNewEnrollments: 'הרשמות חדשות',
  adminStat30d: 'ב־30 הימים האחרונים',
  adminActivityTitle: 'פעילות אחרונה',
  adminActivitySubtitle: 'עדכונים שוטפים מהתלמידים שלכם',
  adminActivityEmpty: 'עוד אין פעילות להציג',
  adminActivityEmptyHint: 'ברגע שתלמידים יירשמו, יצפו וישאלו — הכול יופיע כאן.',
  adminAllSections: 'כל האזורים',
  // API keys + auto-enroll
  apiPageTitle: 'API ואוטומציות',
  apiPageSubtitle: 'חברו דפי תשלום ומערכות חיצוניות — רכישה בחוץ נהיית הרשמה אוטומטית כאן.',
  apiKeysTitle: 'מפתחות API',
  apiKeysSubtitle: 'המפתח מזהה את בית הספר שלכם בקריאות חיצוניות. שומרים אותו כמו סיסמה.',
  apiKeyName: 'שם המפתח',
  apiKeyNamePlaceholder: 'לדוגמה: Make.com — דף מכירה',
  apiKeyCreate: 'ייצור מפתח חדש',
  apiKeyMintedNote: 'זה המפתח — הוא מוצג פעם אחת בלבד. העתיקו ושמרו אותו עכשיו.',
  apiKeysEmpty: 'אין עדיין מפתחות API',
  apiKeysEmptyHint: 'צרו מפתח ראשון כדי לחבר דף תשלום או אוטומציה חיצונית.',
  apiKeyPrefix: 'מפתח',
  apiKeyCreatedAt: 'נוצר',
  apiKeyLastUsed: 'שימוש אחרון',
  apiSnippetTitle: 'מחולל אוטומציות',
  apiSnippetSubtitle: 'בוחרים קורסים — ומקבלים קוד מוכן להדבקה שרושם את הקונה אוטומטית.',
  apiSnippetPickCourses: 'אילו קורסים לרשום בקריאה?',
  apiSnippetNoCourses: 'עוד אין קורסים — צרו קורס ואז חזרו לכאן.',
  adminItemApiDesc: 'מפתחות API וחיבור דפי תשלום חיצוניים.',

  // email automations ("learning reminders")
  remindersTitle: 'תזכורות למידה',
  remindersSubtitle: 'מיילים אוטומטיים שמחזיקים את התלמידים בקצב — גם כשאתם לא מול המסך.',
  automationNew: 'אוטומציה חדשה',
  automationEdit: 'עריכת אוטומציה',
  automationsEmpty: 'עוד אין אוטומציות',
  automationsEmptyHint: 'צרו תזכורת ראשונה — למשל מייל ברוכים הבאים, או עידוד אחרי כמה ימים בלי למידה.',
  automationName: 'שם האוטומציה',
  automationNamePlaceholder: 'לדוגמה: תזכורת חוסר פעילות 3 ימים',
  automationTrigger: 'מתי לשלוח',
  automationTriggerWelcomeOption: 'ברוכים הבאים — בהרשמה הראשונה לקורס',
  automationTriggerInactivityOption: 'תזכורת — אחרי X ימים בלי למידה',
  automationTriggerWelcome: 'נשלח בהרשמה הראשונה',
  automationTriggerInactivity: 'נשלח אחרי {days} ימים בלי למידה',
  automationDays: 'ימים בלי פעילות',
  automationSubject: 'נושא המייל',
  automationBody: 'תוכן המייל',
  automationVarsHint: 'אפשר לשלב משתנים: {{name}} — שם התלמיד, {{org_name}} — שם בית הספר, {{course_title}} — שם הקורס (בברוכים הבאים), {{days}} — ימי חוסר הפעילות.',
  automationActive: 'פעיל',
  automationSent: 'נשלחו',
  adminItemRemindersDesc: 'מיילים אוטומטיים: ברוכים הבאים ותזכורות חוסר פעילות.',

  // terms gate
  termsDefaultTitle: 'תקנון בית הספר',
  termsGateSubtitle: 'רגע אחד לפני שנכנסים — נשאר רק לאשר את תנאי השימוש.',
  termsAgreeLabel: 'קראתי ואני מאשר/ת את התקנון ותנאי השימוש',
  termsAcceptCta: 'מאשרים וממשיכים ללמוד',
  termsAccepting: 'רגע...',
  termsFullLink: 'לקריאת התקנון המלא',
  termsSettingsTitle: 'תקנון / חוזה',
  termsSettingsSubtitle: 'כשהתקנון פעיל, כל תלמיד יידרש לאשר אותו לפני הכניסה לשיעורים.',
  termsEnable: 'דרישת אישור תקנון',
  termsEnabledNote: 'התקנון פעיל — תלמידים חדשים יתבקשו לאשר',
  termsDisabledNote: 'התקנון כבוי — אין חסימה',
  termsTitleLabel: 'כותרת התקנון',
  termsBodyLabel: 'טקסט התקנון',
  termsBodyHint: 'תומך בכמה שורות. שווה לצרף גם קישור לתקנון המלא בנפרד.',
  termsUrlLabel: 'קישור לתקנון מלא (לא חובה)',
  termsBumpVersion: 'החתמה מחדש של כולם',
  termsBumpVersionHint: 'מעלה את גרסת התקנון — כל התלמידים יתבקשו לאשר שוב בכניסה הבאה.',

  // students CSV import
  importCsv: 'ייבוא מ-CSV',
  importCsvTitle: 'ייבוא תלמידים מקובץ',
  importCsvLabel: 'שורה לכל תלמיד: אימייל, ואופציונלית שם אחרי פסיק',
  importCsvHint: 'אפשר להדביק ישר מאקסל או מגוגל שיטס. עד 500 תלמידים בבת אחת.',
  importAction: 'ייבוא',
  importing: 'מייבאים...',
  importDone: 'הייבוא הסתיים',
  importCreated: 'נוספו',
  importPasswordsNote: 'לכל תלמיד חדש נוצרה סיסמה זמנית — היא מוצגת כאן פעם אחת בלבד.',
  importStatusCreated: 'נוסף ✓',
  importStatusExists: 'כבר קיים',
  importCopyPasswords: 'העתקת כל הסיסמאות',

  // branding studio
  brandingTitle: 'מיתוג ועיצוב',
  brandingSubtitle: 'התאימו את המראה של בית הספר למותג שלכם — התלמידים יזכרו אתכם, לא את הפלטפורמה.',
  brandingLogo: 'לוגו בית הספר',
  brandingLogoHint: 'יופיע בסרגל העליון ובעמוד הכניסה. תמונה קטנה, רקע שקוף עובד הכי טוב.',
  brandingUpload: 'העלאת לוגו',
  brandingRemoveLogo: 'הסרה',
  brandingLogoTooBig: 'התמונה גדולה מדי — נסו תמונה קטנה או פשוטה יותר.',
  brandingLogoSize: 'גודל הלוגו',
  brandingPrimary: 'צבע ראשי',
  brandingPrimaryHint: 'הצבע שיצבע את עמוד הבית של התלמידים ואת כפתורי הפעולה.',
  brandingPrimaryClear: 'חזרה לצבע הבסיסי',
  brandingPreview: 'תצוגה מקדימה חיה',
  brandingReset: 'איפוס למראה הבסיסי',
  adminItemBrandingDesc: 'לוגו וצבעים של בית הספר — איך שהתלמידים רואים אתכם.',

  activityEnrolled: 'הצטרפות לקורס',
  activityJoined: 'תלמיד/ה חדש/ה בבית הספר',
  activityPurchase: 'רכישה חדשה',
  activityReview: 'ביקורת חדשה',
  activityQuestion: 'שאלה חדשה בשיעור',

  // owner admin — 4 nav sections + their sub-items
  adminSectionCoursesDesc: 'צרו קורסים חדשים ונהלו את הקיימים.',
  adminSectionStudentsDesc: 'תלמידים, מכשירים מחוברים וקהילה.',
  adminSectionMarketingDesc: 'תשלומים, הודעות, קודי גישה ונתונים.',
  adminSectionSettingsDesc: 'עמוד הבית, וואטסאפ והגדרות בית הספר.',
  adminItemCoursesListDesc: 'רשימת כל הקורסים שלכם, כולל סטטוס פרסום.',
  adminItemCoursesNewDesc: 'התחילו אשף יצירת קורס חדש, שלב אחר שלב.',
  adminItemStudentsDesc: 'רשימת התלמידים הרשומים, הרשמות וגישה.',
  adminItemSessionsDesc: 'מי מחובר עכשיו, ומאיזה מכשיר.',
  adminItemCommunityDesc: 'שאלות ותשובות של תלמידים בתוך הקורסים.',
  adminItemPaymentsDesc: 'רכישות ותשלומים לפי קורס.',
  adminItemBroadcastsDesc: 'שליחת הודעות לכל התלמידים או לקבוצה.',
  adminItemAccessCodesDesc: 'קודי גישה וקופונים לקורסים.',
  adminItemAnalyticsDesc: 'התקדמות תלמידים ונתוני הרשמה.',
  adminItemHomepageDesc: 'עריכת עמוד הבית של בית הספר.',
  adminItemWhatsappDesc: 'חיבור והודעות וואטסאפ.',
  adminItemSettingsDesc: 'הגדרות כלליות של בית הספר.',

  studentPhoneLabel: 'וואטסאפ (לא חובה)',
  studentPhoneHint: 'עם מספר — מנטור ג׳ניריסקול יזהה את התלמיד כשיכתוב לוואטסאפ של בית הספר.',

  // lesson transcription (Gemini → mentor brain)
  transcriptionSync: 'סנכרון תמלולים',
  transcriptionSyncHint: 'ממלא תמלול לכל שיעור וקובץ שעדיין חסר לו — כך המנטור עונה גם מתוך מה שנאמר בווידאו',
  transcriptionSyncing: 'מסנכרן…',
  transcriptionSyncDone: 'נוספו לתור: {lessons} שיעורים ו-{files} קבצים',
  transcriptionSyncNone: 'הכול מתומלל — אין מה לסנכרן',
  transcriptStatusPending: 'ממתין לתמלול',
  transcriptStatusProcessing: 'מתמלל עכשיו…',
  transcriptStatusCompleted: 'תומלל',
  transcriptStatusFailed: 'התמלול נכשל — סנכרון ינסה שוב',

  // AI mentor (WhatsApp, per school)
  mentorGreeting: 'היי {name} 👋 כאן המנטור של בית הספר — אני עונה על שאלות מתוך הקורסים שלך.\n\nעל איזה קורס נדבר?',
  mentorPickHint: 'השיבו עם מספר הקורס. בכל שלב אפשר לכתוב "תפריט" כדי להחליף קורס.',
  mentorSingleCourse: 'היי {name} 👋 כאן המנטור של הקורס "{course}". שאלו אותי כל דבר מתוך הקורס — אני כאן.',
  mentorCourseBound: 'מעולה! אני המנטור של "{course}". מה השאלה הראשונה?',
  mentorCapReached: 'שאלתם המון היום — וזה נהדר! נמשיך מחר, ובינתיים אפשר לחזור לשיעורים או לשאול את המרצה דרך עמוד השיעור.',
  mentorUnavailable: 'המנטור נח כרגע. נסו שוב עוד רגע, או שאלו את המרצה דרך עמוד השיעור.',
  mentorFooter: '— המנטור · "תפריט" להחלפת קורס',
  // {ts} already includes its own " — mm:ss" separator when present (empty string otherwise)
  mentorSourceLine: 'מקור: {lesson}{ts}',

  mentorBudgetStudentMsg: 'המנטור הגיע למכסת השימוש החודשית של בית הספר. בינתיים אפשר לשאול את המרצה דרך עמוד השיעור — או לבקש מבית הספר להרחיב את המכסה.',
  mentorBudgetNotifyTitle: 'תקציב מנטור ג׳ניריסקול לחודש נוצל',
  mentorBudgetNotifyBody: 'מנטור ג׳ניריסקול הגיע לתקרת השימוש החודשית והושהה עד תחילת החודש הבא. רוצים שהוא ימשיך לענות לתלמידים כבר עכשיו? אפשר להרחיב את המכסה:',

  // superadmin — mentor costs panel
  saCostsNav: 'עלויות',
  saCostsTitle: 'עלויות ותקציבי מנטור ג׳ניריסקול',
  saCostsSubtitle: 'כמה עולה מנטור ג׳ניריסקול החודש, לכל בית ספר — והתקרה שמגינה עליכם.',
  saCostsTotal: 'עלות החודש (כל בתי הספר)',
  saCostsMessages: 'תשובות מנטור החודש',
  saCostsOverBudget: 'בתי ספר שמיצו תקציב',
  saCostsSchool: 'בית ספר',
  saCostsUsage: 'שימוש',
  saCostsCost: 'עלות',
  saCostsBudget: 'תקציב חודשי ($)',
  saCostsMsgs: 'תשובות',
  saCostsEmpty: 'אין עדיין שימוש במנטור החודש',
  saCostsEmptyHint: 'ברגע שתלמיד ידבר עם המנטור בוואטסאפ — המספרים יופיעו כאן.',
  saCostsTopupLink: 'קישור תשלום להרחבת מכסה (Grow)',
  saCostsTopupHint: 'יישלח לבעלי בתי ספר שמיצו את התקציב. ריק = יוצגו בלי קישור.',
  saCostsBudgetSaved: 'התקציב עודכן',

  // platform lead bot (WhatsApp scheduling)
  leadBotGreeting:
    'היי {name}, כאן GeniriSchool 👋\nתודה שפניתם אלינו! נשמח לקבוע שיחת היכרות קצרה ולהראות לכם איך מקימים בית ספר דיגיטלי שמוכר.\n\nמתי נוח לכם?',
  leadBotPickHint: 'פשוט השיבו עם המספר של המועד שמתאים לכם. אפשר גם לכתוב "נציג" ונחזור אליכם אישית.',
  leadBotConfirmed: 'מעולה, קבענו! נדבר ב{slot}. נשלח תזכורת לפני, ואם צריך לשנות — כתבו "שינוי".',
  leadBotCalcomGreeting:
    'היי {name}, כאן GeniriSchool 👋\nתודה שפניתם אלינו! נשמח לקבוע שיחת היכרות קצרה ולהראות לכם איך מקימים בית ספר דיגיטלי שמוכר.\n\nבוחרים זמן שנוח לכם ביומן, כאן:\n{url}\n\nצריכים עזרה? כתבו "נציג" ונחזור אליכם אישית.',
  leadBotAlreadyScheduled: 'הפגישה שלנו קבועה ל{slot}. לשינוי המועד כתבו "שינוי", ולכל דבר אחר — "נציג".',
  leadBotHuman: 'אין בעיה — נציג אנושי יחזור אליכם בהקדם. תודה על הסבלנות!',
  leadBotAdminAlert: 'נקבעה פגישה חדשה!\nליד: {name}\nטלפון: {phone}\nמועד: {slot}',

  // superadmin — packages config
  saPackagesNav: 'חבילות',
  saPackagesTitle: 'חבילות ותשלום',
  saPackagesSubtitle: 'המחירים וקישורי התשלום (Grow) שמוצגים לבעלי בתי הספר — נשמרים מיידית לכל המערכת.',
  saPackagePrice: 'מחיר לתצוגה',
  saPackagePriceHint: 'טקסט חופשי, למשל ‎₪49. הסכום בפועל נקבע בקישור התשלום.',
  saPackageLink: 'קישור תשלום (Grow)',
  saPackageLinkHint: 'ריק = יוצג "דברו איתנו להפעלה" במקום כפתור רכישה.',
  saPackagesInvalid: 'השמירה נכשלה — ודאו שהקישורים תקינים (כתובת מלאה עם https).',
  saPackagesFlowNote:
    'זרימת הפעלה: לקוח משלם בקישור Grow ← ה-webhook מזהה את החבילה לפי הסכום ואת בית הספר לפי אימייל הבעלים ← החבילה מופעלת אוטומטית. תשלום שלא זוהה מופיע בטבלה למטה לטיפול ידני (הענקה בעמוד בתי הספר).',
  saWebhookTitle: 'Webhook לתשלומי חבילות',
  saWebhookHint:
    'מדביקים את הכתובת הזו כ-server callback בכל עמוד תשלום של חבילה ב-Grow — כתובת אחת לכל החבילות, כולל כל חיוב של הוראת קבע.',
  saWebhookMissing:
    'לא הוגדר PLAN_WEBHOOK_SECRET בשרת — הוסיפו את המשתנה כדי להפעיל את ה-webhook (ראו .env.example).',
  saWebhookCopy: 'העתקת כתובת',
  saWebhookCopied: 'הועתק ✓',
  saPlanPaymentsTitle: 'תשלומי חבילות שהתקבלו',
  saPlanPaymentsEmpty: 'עוד לא התקבלו תשלומים דרך ה-webhook.',
  saPlanPaymentsSchool: 'בית ספר',
  saPlanPaymentsPlan: 'חבילה',
  saPlanPaymentsAmount: 'סכום',
  saPlanPaymentsPayer: 'משלם',
  saPlanPaymentsCount: 'תשלום מס׳',
  saPlanPaymentsWhen: 'מתי',
  saPlanPaymentsUnmatched: 'לא זוהה — טיפול ידני',

  // superadmin — leads panel
  saLeadsTitle: 'לידים ופגישות',
  saLeadsSubtitle: 'פניות מדף הבית, והבוט שקובע איתן פגישות בוואטסאפ.',
  saLeadsNav: 'לידים',
  saWaTitle: 'וואטסאפ של הפלטפורמה',
  saWaSubtitle: 'סרקו את הקוד עם המספר שממנו הבוט ידבר עם לידים.',
  saLeadName: 'שם',
  saLeadContact: 'יצירת קשר',
  saLeadStatus: 'סטטוס',
  saLeadAppointment: 'פגישה',
  saLeadCreated: 'התקבל',
  saLeadStatusNew: 'חדש',
  saLeadStatusGreeted: 'בשיחה עם הבוט',
  saLeadStatusScheduled: 'פגישה נקבעה',
  saLeadStatusClosed: 'עבר לנציג',
  saLeadsEmpty: 'אין עדיין לידים',
  saLeadsEmptyHint: 'ברגע שמישהו ישאיר פרטים בדף הבית — הוא יופיע כאן.',
  saCalcomTitle: 'יומן פגישות (Cal.com)',
  saCalcomSubtitle: 'כשהיומן מחובר, הבוט שולח ללידים קישור לקביעת פגישה אמיתית ביומן — במקום להציע מועדים בעצמו.',
  saCalcomUrl: 'קישור לדף הקביעה',
  saCalcomUrlHint: 'למשל ‎https://cal.com/your-name/intro — זה הקישור שהבוט ישלח ללידים.',
  saCalcomSecret: 'סוד החתימה (Webhook Secret)',
  saCalcomSecretHint: 'אותו סוד שהגדרתם ב-Cal.com תחת Webhooks — מאמת שההזמנות באמת מגיעות מהיומן.',
  saCalcomWebhookUrl: 'כתובת ה-Webhook להדבקה ב-Cal.com (אירועים: נקבע, בוטל, הוזז)',
  saCalcomActive: 'היומן מחובר — הבוט שולח קישור',
  saCalcomInactive: 'ללא יומן — הבוט מציע מועדים בעצמו',

  // self-serve signup
  signupTitle: 'פותחים בית ספר דיגיטלי',
  signupSubtitle: 'חינם להתחלה — בונים את הקורס, ומשלמים רק כשמתחילים לצרף תלמידים.',
  signupSchoolName: 'שם בית הספר',
  signupSlug: 'כתובת בית הספר',
  signupSlugHint: 'אותיות באנגלית, מספרים ומקפים. זו הכתובת שהתלמידים יקבלו.',
  signupYourName: 'השם שלכם',
  signupCta: 'פתיחת חשבון חינם',
  signupCreating: 'מקימים את בית הספר...',
  signupSlugTaken: 'הכתובת הזו כבר תפוסה — נסו וריאציה אחרת.',
  signupHaveAccount: 'כבר יש לכם בית ספר?',
  signupLoginHint: 'נכנסים דרך הכתובת שלו: ‎/t/שם-בית-הספר',
  signupPanelTitle: 'בונים חינם. משלמים רק כשמוכרים.',
  signupPanelText: 'קורסים, דפי מכירה וסליקה — הכול מוכן. חבילה נדרשת רק כדי לצרף תלמידים ולפרסם את דף המכירה.',

  // packages / plans
  planPageTitle: 'החבילה שלכם',
  planPageSubtitle: 'בונים חינם בלי הגבלה. חבילה נדרשת כדי לצרף תלמידים ולפרסם דפי מכירה.',
  planCurrentLabel: 'החבילה הנוכחית',
  planFree: 'חינם',
  planStarter: 'התחלה',
  planGrowth: 'צמיחה',
  planUnlimited: 'ללא תקרה',
  planFreeDesc: 'בונים את הקורס, מעלים שיעורים ומכינים דף מכירה — בלי תשלום ובלי הגבלת זמן.',
  planStarterDesc: 'לקורס הראשון עם קהל אמיתי — כל היכולות, עד 50 תלמידים.',
  planGrowthDesc: 'לבית ספר שמתרחב — כל היכולות כולל מנטור ג׳ניריסקול, עד 500 תלמידים.',
  planUnlimitedDesc: 'בלי תקרת תלמידים ובלי הפתעות — כולל מנטור ג׳ניריסקול, למותגים שרצים קדימה.',
  planPerMonth: 'לחודש',
  planUpTo: 'עד',
  planStudentsCap: 'תלמידים',
  planNoCap: 'תלמידים ללא הגבלה',
  planChoose: 'לרכישת החבילה',
  planContactToBuy: 'דברו איתנו להפעלה',
  planActivationNote: 'לאחר התשלום נפעיל את החבילה שלכם תוך יום עסקים. שילמתם וטרם הופעל? כתבו לנו.',
  planCurrentBadge: 'החבילה שלכם',
  planStudentsUsed: 'תלמידים רשומים',

  // paywall
  paywallTitle: 'הגעתם לרגע האמת — צירוף תלמידים',
  paywallPublishTitle: 'פרסום דף המכירה דורש חבילה',
  paywallBody: 'בניתם את הקורס — עכשיו נשאר לבחור חבילה כדי לצרף תלמידים ולהתחיל למכור.',
  paywallLimitTitle: 'הגעתם לתקרת התלמידים של החבילה',
  paywallLimitBody: 'החבילה הנוכחית מלאה ({current}/{cap}). משדרגים — וממשיכים לצרף בלי לעצור.',
  paywallCta: 'לצפייה בחבילות',

  // superadmin plan control
  saPlanLabel: 'חבילה',
  saPlanGrantHint: 'שינוי חבילה נכנס לתוקף מיידית — כולל הענקה חינם.',

  // landing pricing section
  lpPricingTitle: 'מתחילים חינם. משלמים כשמוכרים.',
  lpPricingSubtitle: 'בונים את הקורס בלי כרטיס אשראי. חבילה נדרשת רק כדי לצרף תלמידים ולפרסם את דף המכירה.',
  lpPricingFreeNote: 'בנייה חופשית · דף מכירה בטיוטה · ללא הגבלת זמן',
  lpPricingPopular: 'הכי נבחרת',
  lpPricingCtaFree: 'פתיחת חשבון חינם',
  lpNavPricing: 'תמחור',

  // platform marketing homepage (/) — sales-led v2
  lpNavFeatures: 'מה יש בפנים',
  lpNavMentor: 'מנטור ג׳ניריסקול',
  lpNavHow: 'איך זה עובד',
  lpNavFaq: 'שאלות',
  lpNavCta: 'דברו איתנו',
  lpHeroPill: 'קורסים · דף מכירה · סליקה · וואטסאפ · אבטחה — מערכת אחת',
  lpHeroKicker: 'המקום שבו הידע שלכם הופך לעסק',
  lpHeroTitle1: 'הידע שלכם שווה כסף.',
  lpHeroTitle2: 'תנו לו מערכת שמוכרת אותו.',
  lpHeroText:
    'קורסים, דפי מכירה, סליקה ישראלית, ניהול תלמידים ואוטומציות — במערכת אחת, בעברית מלאה. אתם מביאים את התוכן; המערכת מוכרת, רושמת, מלווה וגובה בשבילכם.',
  lpHeroCta: 'דברו איתנו — מקימים לכם בית ספר',
  lpHeroSecondary: 'מה יש בפנים',
  lpHeroTrust1: 'בלי עמלות על מכירות',
  lpHeroTrust2: 'עברית ו־RTL מלאים',
  lpHeroTrust3: 'התוכן והנתונים נשארים שלכם',

  lpStat1Value: '0%',
  lpStat1Label: 'עמלה על המכירות שלכם',
  lpStat2Value: 'דקות',
  lpStat2Label: 'מהקמת קורס לדף מכירה חי',
  lpStat3Value: '100%',
  lpStat3Label: 'עברית, מימין לשמאל',
  lpStat4Value: '24/7',
  lpStat4Label: 'בית הספר מוכר גם כשאתם ישנים',

  lpFeaturesTitle: 'כל העסק שלכם. מערכת אחת.',
  lpFeaturesNote: 'וכל יכולת כאן היא חלק מהמערכת — לא תוסף בתשלום נפרד.',
  lpFeaturesSubtitle: 'בלי לתפור חמישה כלים אחד לשני — הכול כבר מחובר ועובד יחד.',

  // the four core systems (pillars strip)
  lpPillarsEyebrow: 'המערכת',
  lpPillarsTitle: 'ארבע מערכות שעובדות יחד',
  lpPillarsSubtitle: 'מכירה, למידה, התמדה וניהול — כל אחת שלמה בפני עצמה, וכולן חולקות את אותם תלמידים ואותם נתונים.',
  lpPillar1Title: 'מוכרים',
  lpPillar1Body: 'דף מכירה לכל קורס, סליקה ישראלית וערוצי הפצה — הרכישה נסגרת אצלכם, בלי אתר חיצוני.',
  lpPillar1Item1: 'דף נחיתה ממותג לכל קורס',
  lpPillar1Item2: 'סליקת Hyp / Grow עם פתיחה אוטומטית',
  lpPillar1Item3: 'שותפים, קופונים וקודי גישה',
  lpPillar2Title: 'מלמדים',
  lpPillar2Body: 'שיעורי וידאו מאובטחים במודולים, חומרי עזר והערות אישיות — וקהילה שצמודה לשיעור עצמו.',
  lpPillar2Item1: 'נגן מאובטח וחומרי עזר',
  lpPillar2Item2: 'הערות וסימניות אישיות',
  lpPillar2Item3: 'שאלות על שיעור ודיוני קהילה',
  lpPillar3Title: 'מחזירים',
  lpPillar3Body: 'רצף למידה, הישגים, לוח מובילים ותעודת סיום — ותזכורת אוטומטית למי שנעלם באמצע.',
  lpPillar3Item1: 'רצף למידה, הישגים ולוח מובילים',
  lpPillar3Item2: 'תעודת סיום להורדה',
  lpPillar3Item3: 'תזכורות והודעות לכל התלמידים',
  lpPillar4Title: 'מנהלים',
  lpPillar4Body: 'תלמידים, מכירות, חיבורים פעילים ומיתוג — הכול מלוח אחד, ו־API לכל מה שנשאר בחוץ.',
  lpPillar4Item1: 'אנליטיקות התקדמות ומכירות',
  lpPillar4Item2: 'ניהול חיבורים פעילים בזמן אמת',
  lpPillar4Item3: 'API ל־Make ול־Zapier',

  // AI mentor showcase section
  lpMentorBadge: 'חדש',
  lpMentorTitle1: 'מנטור ג׳ניריסקול — עוזר אישי לכל תלמיד.',
  lpMentorTitle2: 'בוואטסאפ שלהם.',
  lpMentorSubtitle:
    'הדבר הכי קרוב לשכפל את עצמכם: עוזר הוראה שלמד את כל הקורסים שלכם ועונה לתלמידים בשמכם — בכל שעה, בעברית.',
  lpMentorPoint1Title: 'עונה רק מתוך התוכן שלכם',
  lpMentorPoint1Body:
    'המנטור מוגבל לחומרי הקורס — התיאור, השיעורים וההערות. בלי המצאות ובלי ידע חיצוני שלא אישרתם.',
  lpMentorPoint2Title: 'כל תשובה מחזירה לשיעור',
  lpMentorPoint2Body:
    'המנטור מציין באיזה שיעור נמצא ההסבר המלא — שאלה הופכת לעוד צפייה בקורס, לא לעוד פנייה אליכם.',
  lpMentorPoint3Title: 'מדבר רק עם תלמידים רשומים',
  lpMentorPoint3Body:
    'זיהוי לפי מספר הטלפון של התלמיד. לכל מספר אחר המנטור שותק — אפשר לחבר גם מספר אישי בראש שקט.',
  lpMentorPoint4Title: 'קם בסריקת QR אחת',
  lpMentorPoint4Body:
    'מחברים את הוואטסאפ של בית הספר פעם אחת — ומאותו רגע לכל תלמיד יש מנטור אישי זמין 24/7.',
  lpMentorPlanNote: 'כלול במסלולי צמיחה וללא תקרה',
  lpMentorCta: 'פותחים בית ספר עם מנטור ג׳ניריסקול',
  lpMentorChatTitle: 'המנטור של בית הספר',
  lpMentorChatStatus: 'מחובר · עונה עכשיו',
  lpMentorChatQ1: 'לא הבנתי את החלק של התמחור בשיעור 3 😅',
  lpMentorChatA1:
    'שאלה מצוינת! בשיעור 3, "בונים הצעת מחיר", מוסבר שמתחילים מהערך ללקוח ולא מהעלות שלכם: קובעים מחיר לפי התוצאה שהקורס נותן. ההסבר המלא נמצא בשיעור 3, החל מהדגמת המחשבון.',
  lpMentorChatQ2: 'ואיפה יש דוגמה מלאה?',
  lpMentorChatA2: 'בשיעור 4, "תמחור בפועל", יש דוגמה מלאה עם מספרים אמיתיים. שווה צפייה 👌',
  lpMentorChatFooter: '— המנטור · זמין לכל תלמיד רשום',
  lpFeatVideoTitle: 'וידאו מאובטח, בלי מגבלות',
  lpFeatVideoBody: 'העלאת שיעורים בכל גודל, נגן מותאם, קבצי עזר לכל שיעור — והתוכן חסום למי שלא שילם.',
  lpFeatLandingTitle: 'דפי מכירה שממירים',
  lpFeatLandingBody: 'לכל קורס דף נחיתה ממותג עם המלצות, גלריה וספירה לאחור — כולל בונה AI שכותב את הדף בשבילכם.',
  lpFeatPayTitle: 'סליקה ישראלית מקצה לקצה',
  lpFeatPayBody: 'חיבור ל־Hyp ו־Grow: הלקוח משלם, החשבון נוצר, הקורס נפתח והקבלה נשלחת — בלי מגע יד.',
  lpFeatWhatsappTitle: 'וואטסאפ, לא רק מייל',
  lpFeatWhatsappBody: 'פרטי כניסה, עדכונים והודעות לכל התלמידים מגיעים ישר לוואטסאפ — לערוץ שבאמת נפתח.',
  lpFeatStudentsTitle: 'ניהול תלמידים בקלות',
  lpFeatStudentsBody: 'הזמנות, ייבוא מ־CSV, איפוס סיסמאות ומעקב התקדמות אישי — הכול בלוח אחד.',
  lpFeatAutomationTitle: 'אוטומציות שמחזירות תלמידים',
  lpFeatAutomationBody: 'מייל ברוכים הבאים אוטומטי, ותזכורת חכמה למי שנעלם כמה ימים — הקורס שומר על עצמו.',
  lpFeatBrandTitle: 'המותג שלכם, לא שלנו',
  lpFeatBrandBody: 'לוגו, צבעים וכתובת משלכם — התלמידים זוכרים אתכם, לא את הפלטפורמה.',
  lpFeatCommunityTitle: 'קהילה ושאלות בתוך הקורס',
  lpFeatCommunityBody: 'דיונים, שאלות על שיעור ותשובות מרצה — הכול נשאר צמוד לתוכן הרלוונטי.',
  lpFeatGamifyTitle: 'תלמידים שמסיימים — וקונים שוב',
  lpFeatGamifyBody: 'רצף למידה, הישגים, לוח מובילים ותעודת סיום — מנועי ההתמדה מובנים במערכת.',
  lpFeatAffiliatesTitle: 'שותפים וקודי גישה',
  lpFeatAffiliatesBody: 'קישורי שותפים עם מעקב כניסות, וקודים להרשמה מיידית — ערוצי מכירה נוספים בלחיצה.',
  lpFeatApiTitle: 'מתחבר לכל מה שיש לכם',
  lpFeatApiBody: 'API עם מחולל קוד מוכן ל־Make ו־Zapier — כל דף תשלום חיצוני יכול לרשום לקוחות אוטומטית.',
  lpFeatAnalyticsTitle: 'רואים מה באמת קורה',
  lpFeatAnalyticsBody: 'התקדמות, השלמות, פעילות ומכירות — מספרים שעוזרים להחליט מה לשפר ומתי לדחוף.',
  lpFeatHomepageTitle: 'עמוד בית משלכם לתלמידים',
  lpFeatHomepageBody: 'הודעת פתיחה, עדכונים והבלטת קורסים — עורכים את עמוד הבית של בית הספר בלי שורת קוד.',
  lpFeatLinksTitle: 'עמוד לינקים ממותג',
  lpFeatLinksBody: 'דף link-in-bio לבית הספר עם הלוגו, הקורסים והרשתות שלכם — קישור אחד לביו באינסטגרם.',
  lpFeatMentorTitle: 'מנטור ג׳ניריסקול בוואטסאפ',
  lpFeatMentorBody: 'תלמיד רשום שואל בוואטסאפ ומקבל תשובה מתוך התוכן שלכם בלבד, עם הפניה לשיעור הנכון.',

  lpHowTitle: 'משלוש החלטות למכונת מכירה',
  lpHowSubtitle: 'בלי מפתחים, בלי בונה אתרים, בלי כאב ראש.',
  lpHowStep1Title: 'בונים את הקורס',
  lpHowStep1Body: 'מעלים שיעורים וחומרים באשף פשוט. בונה ה־AI מנסח לכם דף מכירה מוכן תוך דקות.',
  lpHowStep2Title: 'מפרסמים את הדף',
  lpHowStep2Body: 'משתפים את דף המכירה בכל ערוץ — רשתות, וואטסאפ, שותפים. כל קליק מגיע לדף שבנוי להמיר.',
  lpHowStep3Title: 'המכירה רצה לבד',
  lpHowStep3Body: 'לקוח משלם — ותוך שניות יש לו חשבון, גישה לקורס והודעת וואטסאפ עם פרטי הכניסה. אתם רק רואים את ההכנסה.',

  lpFlowTitle: 'מה קורה כשמישהו קונה?',
  lpFlowSubtitle: 'התהליך שרץ אוטומטית על כל מכירה, יום ולילה.',
  lpFlowStep1: 'הלקוח משלם בדף מאובטח (Hyp / Grow)',
  lpFlowStep2: 'נוצר לו חשבון והקורס נפתח — מיידית',
  lpFlowStep3: 'פרטי הכניסה נשלחים בוואטסאפ ובמייל',
  lpFlowStep4: 'מייל ברוכים הבאים יוצא, וההתקדמות מתחילה להימדד',
  lpFlowNote: 'ואם הלקוח נעלם לכמה ימים? תזכורת אוטומטית מחזירה אותו לשיעור.',

  lpTrustTitle: 'והשקט הנפשי? מובנה.',
  lpTrustSubtitle: 'ההכנסה שלכם מוגנת ברמת התשתית — לא כתוספת.',
  lpTrust1Title: 'סיסמה אחת לא הופכת לעשרה צופים',
  lpTrust1Body: 'מכסת מכשירים חכמה לכל חשבון: מכשיר חורג נחסם ברגע האמת, ואפשר לנתק כל חיבור בלחיצה.',
  lpTrust2Title: 'התוכן נעול למשלמים בלבד',
  lpTrust2Body: 'וידאו בקישורים חתומים שפגים מעצמם — אי אפשר להעביר קישור הלאה ולצפות בחינם.',
  lpTrust3Title: 'הנתונים שלכם מבודדים לגמרי',
  lpTrust3Body: 'כל בית ספר חי בסביבה נפרדת עם שתי שכבות בידוד עצמאיות, עד רמת מסד הנתונים.',

  lpFaqTitle: 'שאלות שכולם שואלים',
  lpFaq1Q: 'כמה עמלה אתם לוקחים על מכירה?',
  lpFaq1A: 'אפס. התשלומים עוברים ישירות בחשבון הסליקה שלכם (Hyp או Grow) — כל שקל שנמכר הוא שלכם.',
  lpFaq2Q: 'צריך אתר או ידע טכני?',
  lpFaq2A: 'לא. בית הספר קם עם כתובת משלו, דפי המכירה נבנים בתוך המערכת, ובונה ה־AI מנסח את התוכן השיווקי בשבילכם.',
  lpFaq3Q: 'אפשר להעביר קורסים שכבר קיימים?',
  lpFaq3A: 'כן. מעלים את הווידאו והחומרים לאשף הקורס, מייבאים את רשימת התלמידים מ־CSV — וממשיכים מאותה נקודה.',
  lpFaq4Q: 'מה קורה אחרי שלקוח משלם?',
  lpFaq4A: 'הכול אוטומטי: חשבון נוצר, הקורס נפתח, ופרטי הכניסה נשלחים בוואטסאפ ובמייל — בלי המתנה ובלי טיפול ידני.',
  lpFaq5Q: 'ואיך מונעים העברת סיסמאות?',
  lpFaq5A: 'כל חשבון מוגבל למספר מסכים פתוחים בו־זמנית. מכשיר חורג נחסם אוטומטית, ואתם רואים בזמן אמת מי מחובר.',
  lpFaq6Q: 'איך עובד מנטור ג׳ניריסקול בוואטסאפ?',
  lpFaq6A:
    'מחברים את הוואטסאפ של בית הספר בסריקת QR — ומרגע זה תלמיד ששולח שאלה מקבל תשובה מתוך תוכן הקורס בלבד, עם הפניה לשיעור המתאים. המנטור מזהה תלמידים רשומים לפי מספר הטלפון ולא עונה לאף אחד אחר.',

  lpFinalTitle: 'מוכנים למכור את הקורס הבא שלכם?',
  lpFinalSubtitle: 'ספרו לנו על הקורס — נקים לכם בית ספר לדוגמה ותראו אותו חי, בלי התחייבות.',
  lpDemoDashTitle: 'מה קורה אצלכם היום',
  lpDemoSaleBadge: 'מכירה חדשה',
  lpDemoStatStudents: 'תלמידים',
  lpDemoStatRevenue: 'הכנסות החודש',
  lpDemoStatCompletion: 'אחוז השלמה',
  lpDemoContinue: 'ממשיכים ללמוד',
  lpDemoGuard: 'מכשיר רביעי ניסה להיכנס עם אותה סיסמה — ונחסם',

  // platform marketing homepage (/)
  platformHeroTitle1: 'בית ספר דיגיטלי משלכם —',
  platformHeroTitle2: 'בלי שהסיסמה תעבור מיד ליד',
  platformHeroText: 'מעלים שיעורי וידאו, מנהלים תלמידים ובונים דפי נחיתה שמוכרים — עם מכסת מכשירים חכמה ששומרת שהתוכן שיצרתם יישאר שלכם, ורק שלכם.',
  platformCtaAdmin: 'כניסת מנהל המערכת',
  platformTenantHint: 'תלמידים ובעלי קורסים נכנסים דרך הכתובת של בית הספר שלהם: ‎/t/שם-בית-הספר',
  platformDemoConnections: '3 מחוברים',
  platformDemoNow: 'עכשיו',
  platformDemoAgoMin: 'לפני דקה',
  platformDemoAgo4Min: 'לפני 4 דקות',
  platformDemoBlocked: 'מכשיר רביעי נחסם — עבר את מכסת המכשירים',
  platformFooterTagline: 'נבנה לבתי ספר דיגיטליים',

  // platform marketing homepage (/) — extended sections
  platformNavHow: 'איך זה עובד',
  platformNavFeatures: 'יכולות',
  platformNavSecurity: 'אבטחה',

  platformStat1Value: '2',
  platformStat1Label: 'שכבות אבטחה — לא אחת',
  platformStat2Value: 'מיידי',
  platformStat2Label: 'חסימת מכשיר חורג',
  platformStat3Value: '24/7',
  platformStat3Label: 'הקורסים שלכם זמינים תמיד',
  platformStat4Value: '0',
  platformStat4Label: 'בתי ספר שרואים נתונים של בית ספר אחר',

  platformHowEyebrow: 'התהליך',
  platformHowTitle: 'משלוש דקות להקמה, לבית ספר דיגיטלי חי',
  platformHowSubtitle: 'בלי מפתחים, בלי שרתים, בלי כאב ראש.',
  platformStep1Title: 'מעלים את הקורס',
  platformStep1Body: 'שיעורי וידאו, חומרי עזר ומבחנים — מאורגנים במודולים, עם דף נחיתה שמוכר את הקורס לתלמידים חדשים.',
  platformStep2Title: 'כל בית ספר בכתובת שלו',
  platformStep2Body: 'כל לקוח מקבל את הכתובת שלו — ‎/t/שם-בית-הספר — עם המיתוג, התלמידים והנתונים שלו בלבד, מבודד לגמרי משאר הלקוחות במערכת.',
  platformStep3Title: 'מכסת המכשירים שומרת על ההכנסה שלכם',
  platformStep3Body: 'כשתלמיד מתחבר ממכשיר רביעי, המערכת חוסמת אותו מיידית — לא מחר, לא אחרי בדיקה ידנית. ברגע האמת.',

  platformFeaturesTitle: 'לא רק פלטפורמת קורסים — פלטפורמה שמגנה על ההכנסה שלכם',
  platformFeaturesSubtitle: 'כל מה שצריך כדי למכור, ללמד ולהישאר מוגנים מהעתקת סיסמאות.',
  platformFeature1Title: 'מכסת מכשירים חכמה',
  platformFeature1Body: 'כל סיסמה מוגבלת למספר מכשירים קבוע. שיתוף חורג נחסם אוטומטית — לא אחרי חודש, ברגע שזה קורה.',
  platformFeature2Title: 'ניתוק מיידי, לא רק חסימה',
  platformFeature2Body: 'מנהל בית הספר יכול לראות מי מחובר עכשיו ולנתק כל מכשיר בלחיצה אחת — בלי לחכות לפג תוקף.',
  platformFeature3Title: 'דף נחיתה שמוכר',
  platformFeature3Body: 'כל קורס מקבל דף מכירה משלו — בלי צורך בבונה אתרים נפרד או באתר חיצוני.',
  platformFeature4Title: 'קודי הצטרפות ושותפים',
  platformFeature4Body: 'קודי גישה לחלוקה ידנית, וקישורי שותפים למי שמפיץ את הקורס עבורכם — עם מעקב מלא.',
  platformFeature5Title: 'עדכונים ישירות לוואטסאפ',
  platformFeature5Body: 'התראות קורס, תזכורות ועדכוני התקדמות נשלחים ישר לוואטסאפ של התלמיד — לא רק למייל שלא נפתח.',
  platformFeature6Title: 'קהילה לכל קורס',
  platformFeature6Body: 'תלמידים שואלים ומגיבים בתוך הקורס עצמו — שאלות, תשובות ודיונים נשארים מסודרים לצד השיעור הרלוונטי.',

  platformSecurityTitle: 'שתי שכבות בידוד. לא אחת.',
  platformSecuritySubtitle: 'רוב הפלטפורמות סומכות על שכבה אחת. אנחנו לא.',
  platformSecurity1Title: 'שכבה 1 — סינון ברמת האפליקציה',
  platformSecurity1Body: 'כל שאילתה למסד הנתונים מסוננת אוטומטית לפי בית הספר של המשתמש המחובר — בלתי אפשרי לגשת בטעות לנתונים של לקוח אחר.',
  platformSecurity2Title: 'שכבה 2 — אבטחה ברמת מסד הנתונים (RLS)',
  platformSecurity2Body: 'גם אם קוד האפליקציה יפספס פילטר, מסד הנתונים עצמו (PostgreSQL Row-Level Security) חוסם את הגישה. השכבה השנייה קיימת בדיוק בשביל הרגע שהראשונה נכשלת.',
  platformSecurity3Title: 'מרשם החיבורים החי',
  platformSecurity3Body: 'כל התחברות נרשמת במרשם חי (Redis) שבודק בכל בקשה האם ההתחברות עדיין תקפה — כך אפשר לחסום או לנתק מכשיר תוך שנייה, בלי להמתין לפקיעת טוקן.',

  platformFinalCtaTitle: 'רוצים לראות את זה על הקורס שלכם?',
  platformFinalCtaSubtitle: 'נשמח להראות איך זה עובד ולהתאים תוכנית שמתאימה לגודל בית הספר שלכם.',
  platformFinalCtaButton: 'דברו איתנו',
  platformFinalCtaNote: 'בלי התחייבות · תשובה תוך יום עסקים',
  platformFooterRights: 'כל הזכויות שמורות.',

  platformLeadFormNameLabel: 'שם',
  platformLeadFormContactLabel: 'טלפון או אימייל',
  platformLeadFormMessageLabel: 'ספרו לנו קצת (לא חובה)',
  platformLeadFormSubmit: 'שלחו לי פרטים',
  platformLeadFormSubmitting: 'שולח...',
  platformLeadFormSuccessTitle: 'תודה!',
  platformLeadFormSuccessBody: 'קיבלנו את הפרטים, נחזור אליכם בקרוב.',
  platformLeadFormErrorBody: 'משהו השתבש בשליחה — נסו שוב או כתבו לנו ישירות.',

  // page metadata
  metaTitle: 'GeniriSchool — פלטפורמת הקורסים שלכם',
  metaDescription: 'פותחים בית ספר דיגיטלי משלכם, מוכרים קורסים, ושומרים על התוכן עם מכסת מכשירים חכמה',

  // landing footer
  landingBuiltWith: 'נבנה עם GeniriSchool',

  // ── payments (Grow webhook → auto-provision + WhatsApp) ──
  payments: 'מכירות ותשלומים',
  paymentsSubtitle: 'כל רכישה פותחת חשבון לתלמיד, רושמת אותו לקורס ושולחת לו את פרטי הכניסה בוואטסאפ ובמייל',
  // payments stats row
  paymentsStatTotal: 'סה״כ הכנסות',
  paymentsStatTotalSub: 'מכל הרכישות שנקלטו',
  paymentsStatMonth: 'הכנסות החודש',
  paymentsStatCount: 'רכישות',
  paymentsStatCountSub: '{n} החודש',
  paymentsStatAvg: 'ממוצע לרכישה',
  paymentsStatNewStudents: 'תלמידים חדשים',

  paymentsHowTitle: 'איך מחברים',
  paymentsHowStep1: 'מעתיקים את כתובת ה-Webhook של הקורס',
  paymentsHowStep2: 'ב-Grow, בדף התשלום של הקורס, מדביקים אותה בשדה ה-Webhook / קריאה חוזרת לשרת',
  paymentsHowStep3: 'זהו — כל תשלום שמאושר יפתח לתלמיד חשבון, ירשום אותו לקורס, וישלח לו בוואטסאפ שם משתמש וסיסמה',
  paymentsHowStep4: 'רוצים שהקונה יראה דף תודה מסודר מיד אחרי התשלום? מדביקים את כתובת דף התודה בשדה ה-Redirect / Return URL בהגדרות הדף ב-Grow (לא חובה)',
  webhookUrlLabel: 'כתובת ה-Webhook של הקורס',
  copyWebhookUrl: 'העתקת הכתובת',
  thankYouUrlLabel: 'כתובת דף התודה (אחרי תשלום)',
  copyThankYouUrl: 'העתקת הכתובת',
  noPaymentLinkYet: 'עדיין לא הוגדר קישור תשלום לקורס הזה — מוסיפים אותו בלשונית השיווק',
  whatsappStatus: 'שליחת וואטסאפ',
  whatsappOn: 'מחוברת ✓',
  whatsappOff: 'לא מוגדרת — פרטי הכניסה יישמרו כאן עד שתחוברת',
  recentSales: 'רכישות אחרונות',
  salePayer: 'רוכש/ת',
  saleCourseCol: 'קורס',
  saleAmount: 'סכום',
  saleDelivered: 'נשלח בוואטסאפ',
  saleNewAccount: 'חשבון חדש',
  noSalesYet: 'עוד אין רכישות — ברגע שמישהו ישלם, זה יופיע כאן',
  abandonedCheckouts: 'לקוחות שעזבו לפני תשלום',
  abandonedCheckoutsHint: 'התחילו בתשלום ומסרו פרטים, אבל לא הגיעו לסליקה בפועל — אפשר לחזור אליהם.',
  noAbandonedCheckouts: 'אין לקוחות שעזבו בזמן האחרון',
  abandonedCheckoutsCaveat:
    'ייתכן שחלק מהם בכל זאת שילמו אך האישור לא הגיע אלינו — מומלץ לבדוק לפני פנייה.',
  saleNotifyTitle: 'מכירה חדשה',
  bundleTitle: 'קישור תשלום אחד לכמה קורסים',
  bundleHint:
    'אם יצרתם ב-Grow קישור תשלום אחד שמכיל כמה מוצרים — מוצר לכל קורס — סמנו כאן את אותם הקורסים והדביקו את הכתובת שנוצרה כ"קולבק" של אותו קישור. כל מי שישלם יקבל גישה לכל הקורסים המסומנים, בחשבון אחד.',
  bundlePick: 'הקורסים שנכללים בקישור',
  bundleNeedTwo: 'סמנו לפחות שני קורסים',
  bundleCatalogHint:
    'רוצים שהקונה יוכל לבחור רק חלק מהמוצרים? הגדירו ב-Grow את "מספר קטלוגי" של כל מוצר למזהה הקורס המופיע כאן, ואז תינתן גישה רק למה שנרכש בפועל.',
  bundleCourseId: 'מזהה הקורס',
  salePhoneLabel: 'טלפון',

  // ── price + bundle (Hyp checkout, replaces the Grow link) ──
  coursePrice: 'מחיר הקורס',
  coursePriceHint: 'המחיר בשקלים שהקונה יחויב בו. אפשר גם עם אגורות, למשל 349.90. השאירו ריק כדי לא למכור את הקורס כרגע.',
  coursePriceCurrency: '₪',
  coursePriceEmpty: 'ללא מחיר — כפתור הרכישה לא יופיע',
  coursePriceSaved: 'המחיר נשמר ✓',
  courseBundleTitle: 'הרכישה כוללת גם',
  courseBundleHint: 'סמנו קורסים נוספים שכל מי שקונה את הקורס הזה יקבל אליהם גישה — במחיר אחד, בתשלום אחד.',
  courseBundleNone: 'אין עדיין קורסים אחרים לצרף',
  courseBundleSummary: 'הקונה יקבל גישה ל-{n} קורסים',
  courseBundlePriceTitle: 'מחיר מיוחד לחבילה',
  courseBundlePriceHint:
    'המחיר שייגבה על כל הקורסים שסימנתם יחד, במקום מחיר הקורס הזה. השאירו ריק כדי לגבות את מחיר הקורס הזה בלבד — והקורסים הנוספים פשוט מצטרפים בחינם.',
  courseBundlePriceSeparately: 'בנפרד: {price}',
  courseAddonsTitle: 'תוספות לבחירת הקונה בקופה',
  courseAddonsHint:
    'קורסים שהקונה יוכל לסמן בעצמו בדף הרכישה ולהוסיף לעסקה — כל אחד בתוספת המחיר שתקבעו כאן. סמנו קורס, וקבעו כמה עולה להוסיף אותו.',
  courseAddonsNone: 'אין עדיין קורסים אחרים להציע כתוספת',
  courseAddonPriceLabel: 'תוספת בשקלים',
  courseAddonNeedsPrice: 'קבעו מחיר לתוספת, אחרת היא לא תוצג בקופה',
  courseAddonInBundle: 'כבר נכלל בחבילה',
  checkoutUrlLabel: 'כתובת דף הרכישה',
  paymentsHypTitle: 'סליקה בכרטיס אשראי (Hyp)',
  paymentsHypConnected: 'מחוברת ✓',
  paymentsHypMissing: 'לא מוגדרת — פנו לתמיכה',
  paymentsHypNote:
    'הקונה ממלא שם, דוא"ל וטלפון בדף הרכישה שלנו, משלם בדף המאובטח של Hyp, וחוזר לדף התודה. החשבון נפתח אוטומטית ופרטי הכניסה נשלחים בוואטסאפ ובמייל.',
  paymentsSetPriceCta: 'להגדרת מחיר — לשונית השיווק של הקורס',

  resendWa: 'שליחה מחדש בוואטסאפ',
  resendSent: 'נשלח! ✓',
  resendQueued: 'ממתין לחיבור וואטסאפ',
  resendFailed: 'השליחה נכשלה — בדקו את הטלפון',

  // super-admin WhatsApp pairing
  whatsappTitle: 'וואטסאפ',
  whatsappSubtitle: 'חיבור מספר וואטסאפ אחד לפלטפורמה — ממנו נשלחים לתלמידים פרטי הכניסה אחרי רכישה',
  waStatusPending: 'מתחבר…',
  waStatusQr: 'ממתין לסריקה',
  waStatusConnected: 'מחובר',
  waStatusDisconnected: 'מנותק',
  waStatusLoggedOut: 'לא מחובר',
  waConnectedAs: 'מחובר כמספר',
  waConnectedNote: 'הכול מוכן — הודעות הכניסה יישלחו אוטומטית מהמספר הזה.',
  waScanHint: 'פותחים וואטסאפ בטלפון ← מכשירים מקושרים ← קישור מכשיר, וסורקים את הקוד',
  waConnectHint: 'לוחצים "התחברות" כדי ליצור קוד QR לסריקה',
  waConnect: 'התחברות',
  waLogout: 'ניתוק המספר',
  waLogoutConfirm: 'לנתק את הוואטסאפ? עד שתחברו מחדש, פרטי כניסה לא יישלחו אוטומטית אחרי רכישה.',

  // WhatsApp message templates (placeholders replaced server-side)
  waWelcomeNew:
    'היי {name}! 🎉\nנרשמת לקורס "{course}".\n\nהכניסה שלך למערכת:\n🔗 {url}\n📧 {email}\n🔑 {pass}\n\nבכניסה הראשונה נבחר יחד סיסמה חדשה משלך. נתראה בפנים! 🚀',
  waWelcomeExisting:
    'היי {name}! 🎉\nנרשמת לקורס "{course}".\n\nאפשר להיכנס עם החשבון הקיים שלך:\n🔗 {url}\n📧 {email}\n\nנתראה בפנים! 🚀',
  waWelcomeNewMulti:
    'היי {name}! 🎉\nנרשמת לקורסים הבאים:\n{courses}\n\nהכניסה שלך למערכת:\n🔗 {url}\n📧 {email}\n🔑 {pass}\n\nבכניסה הראשונה נבחר יחד סיסמה חדשה משלך. שני הקורסים כבר מחכים לך בפנים! 🚀',
  waWelcomeExistingMulti:
    'היי {name}! 🎉\nנרשמת לקורסים הבאים:\n{courses}\n\nאפשר להיכנס עם החשבון הקיים שלך:\n🔗 {url}\n📧 {email}\n\nהכול כבר מחכה לך בפנים! 🚀',

  // Email templates (placeholders replaced server-side)
  mailBuyerSubject: 'הגישה שלך לקורס "{course}" מוכנה',
  mailBuyerNew:
    'היי {name},\n\nתודה על ההרשמה לקורס "{course}"! הגישה שלך מוכנה.\n\nכניסה למערכת: {url}\nאימייל: {email}\nסיסמה זמנית: {pass}\n\nבכניסה הראשונה תתבקש/י לבחור סיסמה חדשה משלך.\nשמרו את המייל הזה עד שתחליפו סיסמה.\n\nבהצלחה ובתיאבון!',
  mailBuyerExisting:
    'היי {name},\n\nתודה על ההרשמה לקורס "{course}"! הקורס נוסף לחשבון הקיים שלך.\n\nכניסה למערכת: {url}\nאימייל: {email}\n\nהסיסמה שלך לא השתנתה.\n\nבהצלחה ובתיאבון!',
  mailBuyerNewMulti:
    'היי {name},\n\nתודה על ההרשמה! הגישה שלך מוכנה לקורסים הבאים:\n{courses}\n\nכניסה למערכת: {url}\nאימייל: {email}\nסיסמה זמנית: {pass}\n\nבכניסה הראשונה תתבקש/י לבחור סיסמה חדשה משלך.\nשמרו את המייל הזה עד שתחליפו סיסמה.\n\nבהצלחה ובתיאבון!',
  mailBuyerExistingMulti:
    'היי {name},\n\nתודה על ההרשמה! הקורסים הבאים נוספו לחשבון הקיים שלך:\n{courses}\n\nכניסה למערכת: {url}\nאימייל: {email}\n\nהסיסמה שלך לא השתנתה.\n\nבהצלחה ובתיאבון!',
  // course catalog number (ties a course to its Grow product)
  catalogNumber: 'מספר קטלוגי',
  catalogNumberHint:
    'העתיקו את המספר הזה לשדה "catalog_number" של המוצר המתאים בגרואו. כך אנחנו יודעים בדיוק איזה קורס נקנה, ותלמיד מקבל רק את מה ששילם עליו.',
  catalogNumberTaken: 'המספר הזה כבר תפוס בקורס אחר. בחרו מספר אחר.',
  catalogNumberInvalid: 'צריך מספר שלם, 1 ומעלה',

  saleUntaggedTitle: 'שימו לב: מכירה ללא מספר קטלוגי ⚠️',
  saleUntaggedBody:
    'בעסקה האחרונה לא זוהה מספר קטלוגי, ולכן ניתנה גישה לכל הקורסים בקישור: {courses}. כדי שתלמיד יקבל רק את מה שקנה — מלאו בגרואו את שדה "catalog_number" של כל מוצר במספר הקטלוגי של הקורס המתאים.',

  mailResetSubject: 'איפוס הסיסמה שלך',
  mailResetBody:
    'קיבלנו בקשה לאיפוס הסיסמה שלך.\n\nלבחירת סיסמה חדשה, היכנסו לקישור הבא:\n{url}\n\nהקישור בתוקף לשעה אחת, ולשימוש חד-פעמי.\nאם לא ביקשתם לאפס סיסמה — אפשר פשוט להתעלם מהמייל הזה. שום דבר בחשבון לא השתנה.\n\nצריכים עזרה? אנחנו כאן בוואטסאפ: {support}',
  mailOwnerSubject: 'מכירה חדשה: {course}',
  mailOwnerBody:
    'מכירה חדשה נרשמה במערכת 🎉\n\nקורס: {course}\nלקוח/ה: {name}\nאימייל: {email}\nטלפון: {phone}\nסכום: {amount}\nמספר עסקה: {txn}\nלקוח/ה חדש/ה: {isNew}\nמשלוח וואטסאפ: {wa}\n\nיומן המכירות: {link}',

  // owner WhatsApp page + message log
  whatsappOwnerSubtitle: 'חברו את הוואטסאפ שלכם — פרטי הכניסה יישלחו לתלמידים מהמספר הזה',
  waMessageLog: 'יומן הודעות',
  waNoMessages: 'עוד לא נשלחו הודעות',
  waMessageBody: 'הודעה',
  waMsgSent: 'נשלח',
  waMsgFailed: 'נכשל',
  waMsgQueued: 'בתור',
  waResend: 'שליחה מחדש',
  // test message
  waTestTitle: 'בדיקת חיבור',
  waTestHint: 'שלחו לעצמכם הודעת בדיקה כדי לוודא שהחיבור עובד',
  waTestPhoneLabel: 'הטלפון שלכם',
  waTestSend: 'שליחת הודעת בדיקה',
  waTestMessage: 'זו הודעת בדיקה מ-GeniriSchool ✅ אם קיבלתם אותה — החיבור עובד מצוין!',
  waTestSent: 'נשלח! בדקו את הוואטסאפ 📱',
  waTestQueued: 'בתור — ממתין לחיבור',
  waTestFailed: 'השליחה נכשלה — בדקו את הטלפון',

  // whatsapp how-it-works help card
  waHelpTitle: 'איך זה עובד',
  waHelpStep1: 'סורקים את קוד ה-QR פעם אחת כדי לחבר את מספר הוואטסאפ שלכם',
  waHelpStep2: 'מכאן כל תלמיד שירכוש קורס יקבל מכם אוטומטית הודעה עם קישור וסיסמה לכניסה',
  waHelpStep3: 'תמיד אפשר לשלוח לעצמכם הודעת בדיקה, ולשלוח כל הודעה מחדש מהיומן',

  // nav group labels
  navMarketing: 'שיווק ומכירות',

  // ── extended features: shared ──
  send: 'שליחה',
  reply: 'תגובה',
  by: 'מאת',
  justNow: 'ממש עכשיו',

  // notifications
  notifications: 'התראות',
  notificationsEmpty: 'אין התראות חדשות',
  markAllRead: 'סימון הכול כנקרא',
  notifsAllRead: 'הכול נקרא ✓',
  viewAllNotifications: 'לכל ההתראות',

  // broadcasts (owner → students)
  broadcasts: 'הודעות לתלמידים',
  broadcastsSubtitle: 'שלחו הודעה לכל התלמידים, או רק לתלמידי קורס מסוים',
  newBroadcast: 'הודעה חדשה',
  broadcastSubject: 'נושא',
  broadcastBody: 'תוכן ההודעה',
  broadcastAudience: 'למי שולחים',
  broadcastAll: 'כל התלמידים',
  broadcastSend: 'יאללה, שולחים',
  broadcastSent: 'ההודעה נשלחה ל-{n} תלמידים',
  broadcastNoRecipients: 'אין תלמידים לשלוח אליהם עדיין',
  broadcastsEmpty: 'עוד לא שלחתם הודעות — הראשונה מחכה',
  broadcastSentTo: 'נשלח ל-{n}',
  broadcastConfirmTitle: 'אישור שליחה',
  broadcastConfirmBody: 'ההודעה תישלח ל: {audience}. אין דרך לבטל אחרי השליחה.',
  broadcastConfirmSend: 'כן, שולחים עכשיו',

  // community
  community: 'קהילה',
  communitySubtitle: 'שאלות, רעיונות ושיחות — כולנו כאן ביחד',
  newPost: 'פוסט חדש',
  postTitle: 'כותרת',
  postBody: 'מה בא לכם לשתף?',
  postPublish: 'פרסום',
  postReplyLabel: 'תגובה',
  replyPlaceholder: 'מוסיפים תגובה...',
  communityEmpty: 'עוד שקט כאן — היו הראשונים לפתוח שיחה',
  pinPost: 'הצמדה',
  unpinPost: 'ביטול הצמדה',
  pinnedBadge: 'מוצמד',
  repliesCount: 'תגובות',
  deletePost: 'מחיקת הפוסט',
  backToCommunity: 'חזרה לקהילה',
  communityModeration: 'ניהול הקהילה',
  roleOwnerBadge: 'צוות',

  // lesson Q&A
  lessonQa: 'שאלות ותשובות',
  askQuestion: 'שאלו כאן',
  questionPlaceholder: 'לא הבנתם משהו? שאלו — ונחזור אליכם',
  sendQuestion: 'שליחת השאלה',
  qaEmpty: 'אין עדיין שאלות על השיעור הזה',
  qaAnswerLabel: 'תשובה',
  qaAnswerPlaceholder: 'כתבו תשובה לתלמיד...',
  qaAnswerSend: 'שליחת תשובה',
  qaAnswered: 'נענתה',
  qaWaiting: 'ממתינה לתשובה',
  qaAskedBy: 'נשאל/ה על ידי',

  // access codes (free-enroll coupons)
  accessCodes: 'קודי גישה',
  accessCodesSubtitle: 'קודים שמאפשרים הרשמה חינם לקורס — למתנות, מכירות ידניות או קמפיינים',
  newAccessCode: 'קוד חדש',
  accessCodeCourse: 'קורס',
  accessCodeMaxUses: 'מספר שימושים',
  accessCodeExpiry: 'תוקף בימים (לא חובה)',
  accessCodeCreate: 'יצירת הקוד',
  accessCodesEmpty: 'עוד לא יצרתם קודים',
  accessCodeUses: 'שימושים',
  accessCodeExpired: 'פג תוקף',
  accessCodeRevoke: 'ביטול הקוד',
  redeem: 'מימוש קוד',
  redeemTitle: 'יש לכם קוד גישה?',
  redeemHint: 'הזינו את הקוד וקבלו גישה מיידית לקורס',
  redeemCode: 'הקוד שלכם',
  redeemSubmit: 'מימוש והצטרפות',
  redeemSuccess: 'הקוד התקבל — נרשמתם לקורס',
  redeemInvalid: 'הקוד לא תקף, כבר נוצל או שפג תוקפו',
  codeCopied: 'הקוד הועתק!',

  // certificates
  certificate: 'תעודה',
  certificatesTitle: 'התעודות שלי',
  certificateHeading: 'תעודת סיום',
  certificateAwardedTo: 'ניתנת בזאת ל־',
  certificateForCompleting: 'על השלמת הקורס',
  certificateIssuedOn: 'הונפקה בתאריך',
  certificateSerial: 'מספר תעודה',
  viewCertificate: 'לצפייה בתעודה',
  printCertificate: 'הדפסה / שמירה כ-PDF',
  certificateReady: 'סיימתם — התעודה שלכם מוכנה',
  noCertificates: 'עוד אין תעודות — סיימו קורס, והראשונה כבר מחכה',
  certificateIssuedBy: 'הונפקה על ידי',

  // lesson navigation
  lessonNavPrev: 'הקודם',
  lessonNavNext: 'הבא',
  jumpToLesson: 'קפיצה לשיעור',
  allCourseLessons: 'כל השיעורים בקורס',
  lessonPositionOf: 'שיעור {i} מתוך {n}',
  lessonNavDone: 'הושלם',
  lessonNavCurrent: 'כאן אתם עכשיו',
  lessonNavLocked: 'עוד נעול',
  closeMenu: 'סגירה',

  // lesson notes (private)
  myNotes: 'הפתקים שלי',
  lessonNotesLabel: 'פתקים אישיים',
  lessonNotesHint: 'כתבו לעצמכם — אף אחד חוץ מכם לא רואה את זה',
  notesSaved: 'הפתק נשמר ✓',
  notesPlaceholder: 'משהו ששווה לזכור מהשיעור...',
  saveNote: 'שמירת הפתק',
  myNotesEmpty: 'עוד לא כתבתם פתקים — הם יופיעו כאן',

  // wishlist
  wishlistTitle: 'לצפייה בהמשך',
  addToWishlist: 'שמירה לרשימה',
  removeFromWishlist: 'הסרה מהרשימה',
  wishlistSaved: 'נשמר לרשימה 🔖',
  wishlistEmpty: 'הרשימה ריקה — הוסיפו קורסים שבא לכם לחזור אליהם',

  // owner analytics
  analytics: 'נתונים ותובנות',
  analyticsSubtitle: 'מבט־על על כל מה שקורה בבית הספר',
  totalStudents: 'סה״כ תלמידים',
  activeStudents7: 'פעילים השבוע',
  activeStudents30: 'פעילים החודש',
  totalEnrollments: 'סה״כ רישומים',
  avgCompletion: 'אחוז השלמה ממוצע',
  // combined landing pages (collections)
  collectionsTitle: 'דף משולב',
  collectionsDesc: 'דף נחיתה אחד שמציג כמה קורסים יחד, עם תשלום נפרד לכל קורס',
  collectionsSubtitle: 'מקדמים כמה קורסים בקישור אחד. כל קורס נשאר עם דף התשלום שלו.',
  collectionNew: 'דף משולב חדש',
  collectionNone: 'עוד אין דפים משולבים',
  collectionNoneHint: 'צריך לפחות שני קורסים כדי לבנות דף משולב',
  collectionTitleLabel: 'שם הדף (פנימי)',
  collectionTitlePlaceholder: 'למשל: כל הקורסים שלי',
  collectionCourses: 'הקורסים בדף',
  collectionCoursesHint: 'בחרו לפחות שניים. הסדר כאן הוא הסדר בדף.',
  collectionCourseUnpriced: 'ללא מחיר — הכפתור יוביל לדף הקורס',
  collectionCourseNoLanding: 'דף הנחיתה של הקורס לא פורסם',
  collectionHero: 'כותרת ופתיח',
  collectionHeadline: 'כותרת ראשית',
  collectionHeadlinePlaceholder: 'בחרו את המסלול שמתאים לכם',
  collectionSubheadline: 'כותרת משנה',
  collectionIntro: 'פסקת פתיחה (אופציונלי)',
  collectionCtaText: 'טקסט הכפתור בכל כרטיס קורס',
  collectionCrossAddons: 'לאפשר להוסיף את הקורסים האחרים בקופה',
  collectionCrossAddonsHint:
    'בדף התשלום של כל קורס יופיעו שאר הקורסים שבדף כתוספת אופציונלית במחירם המלא. משפיע רק על קורסים עם מחיר.',
  collectionPublished: 'הדף באוויר',
  collectionPublish: 'פרסום הדף',
  collectionUnpublish: 'הורדה מפרסום',
  collectionSaveFirst: 'שומרים קודם, ואז אפשר לפרסם',
  collectionDeleted: 'הדף נמחק',
  collectionCoursesCount: '{n} קורסים',
  collectionCoursesCountTwo: 'שני קורסים',
  collectionChooseCourse: 'בחרו את הקורס שמתאים לכם',
  collectionChooseCourseCta: 'לבחירת קורס',
  collectionNavCourses: 'הקורסים',
  collectionFrontCourse: 'הקורס שהתוכן שלו יוצג בדף',
  collectionFrontCourseHint: 'הדף נבנה מדף הנחיתה של הקורס הזה (עיצוב, טקסטים, גלריה) — בלי "סקשנים נוספים" ו"למה דווקא אצלנו". השעות והשיעורים מסוכמים מכל הקורסים.',
  collectionFrontBadge: 'מוצג בדף',
  collectionPriceFrom: 'החל מ־{price}',
  collectionSectionTitle: 'הקורסים שלנו',
  collectionEachSeparate: 'כל קורס נרכש בנפרד — ובקופה אפשר להוסיף גם את השאר',
  collectionPickAnother: 'אפשר להוסיף גם:',
  collectionToCourse: 'לפרטים המלאים',
  collectionMinCourses: 'צריך לבחור לפחות שני קורסים',
  collectionSaveFailed: 'השמירה נכשלה — נסו שוב',
  salesFunnel: 'משפך מכירות',
  salesFunnelHint: 'מבקרים ייחודיים בכל שלב, לכל קורס: עמוד נחיתה ← דף תשלום ← התחילו תשלום ← שילמו',
  funnelLanding: 'עמוד נחיתה',
  funnelCheckout: 'דף תשלום',
  funnelStarted: 'התחילו תשלום',
  funnelPaid: 'שילמו',
  funnelConversion: 'המרה',
  funnelDropCheckout: 'נטשו בדף התשלום',
  collectionViews: 'צפיות בדף משולב',
  analyticsLessonsCompleted: 'שיעורים שהושלמו',
  totalLearningMinutes: 'דקות למידה בסך הכול',
  completionByCourse: 'השלמה לפי קורס',
  certificatesIssued: 'תעודות שהונפקו',
  linktreeViews: 'צפיות בעמוד הלינקטרי',
  landingViews: 'צפיות בעמוד',
  analyticsNoData: 'עוד אין מספיק נתונים להצגה',

  // super-admin platform stats
  platformStats: 'נתוני הפלטפורמה',
  totalTenants: 'בתי ספר',
  totalUsers: 'משתמשים',
  totalCoursesStat: 'קורסים',
  liveNow: 'מחוברים כרגע',

  // leaderboard
  leaderboard: 'טבלת המובילים',
  leaderboardSubtitle: 'מי צובר הכי הרבה? כל שיעור מקרב אתכם לצמרת',
  leaderboardEmpty: 'הטבלה עוד מתמלאת — סיימו שיעורים כדי לטפס',
  rankLabel: 'מקום',
  learnerLabel: 'תלמיד/ה',
  youLabel: 'אתם',
  leaderLessonsLabel: 'שיעורים',

  // AI Builder — wizard that drafts landing/home-page copy with Gemini
  aiBuilderTitle: 'בניית AI',
  aiBuilderSubtitle: 'כמה שאלות קצרות — ותוך רגע יש טיוטת תוכן מלאה שאפשר לאשר או לערוך',
  aiBuilderOpen: 'בואו נבנה עם AI',
  aiBuilderStepGoal: 'מה המטרה העיקרית?',
  aiBuilderGoalSales: 'למכור',
  aiBuilderGoalSalesHint: 'מבקר שצריך להחליט לקנות עכשיו',
  aiBuilderGoalTrust: 'לבנות אמון',
  aiBuilderGoalTrustHint: 'מבקר ספקן שצריך עוד ביטחון',
  aiBuilderGoalExplain: 'להסביר',
  aiBuilderGoalExplainHint: 'מבקר שעוד לא הבין בדיוק מה זה',
  aiBuilderGoalRecruit: 'למשוך קהל מתאים',
  aiBuilderGoalRecruitHint: 'למשוך את התלמידים הנכונים, לא כל מי שיזדמן',
  aiBuilderStepTone: 'איזה טון מתאים?',
  aiBuilderToneWarm: 'חם ואישי',
  aiBuilderToneProfessional: 'מקצועי וסמכותי',
  aiBuilderToneBold: 'נועז ואנרגטי',
  aiBuilderToneMinimal: 'מינימלי ורגוע',
  aiBuilderStepCreativity: 'כמה חופש יצירתי לתת ל-AI?',
  aiBuilderCreativitySafe: 'בטוח ומדויק',
  aiBuilderCreativitySafeHint: 'צמוד לעובדות שסיפקתם',
  aiBuilderCreativityBalanced: 'מאוזן',
  aiBuilderCreativityBold: 'נועז ויצירתי',
  aiBuilderCreativityBoldHint: 'ניסוחים אמיצים יותר',
  aiBuilderStepDetails: 'עוד כמה פרטים (לא חובה)',
  aiBuilderAudienceHint: 'קהל היעד',
  aiBuilderAudienceHintPlaceholder: 'למשל: הורים לילדים בגיל הגן',
  aiBuilderSellingPoints: 'מה מייחד אתכם?',
  aiBuilderSellingPointsPlaceholder: 'למשל: שיטה ייחודית, רקע מקצועי, גישה אישית',
  aiBuilderBack: 'חזרה',
  aiBuilderNext: 'הבא',
  aiBuilderGenerate: 'יצירת טיוטה',
  aiBuilderGenerating: 'ה-AI כותב טיוטה... זה לוקח כמה שניות',
  aiBuilderFailed: 'יצירת הטיוטה נכשלה. ננסה שוב?',
  aiBuilderPreviewTitle: 'הצצה לטיוטה',
  aiBuilderPreviewHint: 'ככה ייראה הדף עם התוכן שנוצר — עוד לא נשמר',
  aiBuilderConfirm: 'אישור ופרסום',
  aiBuilderEditFirst: 'פתיחה לעריכה',
  aiBuilderStartOver: 'שאלות מחדש',
  aiBuilderDisabled: 'בניית AI לא מופעלת בשרת הזה',
  aiBuilderAppliedNotice: 'הטיוטה נטענה לטופס למטה — אפשר לערוך ואז לשמור',
  aiBuilderConfirmedNotice: 'הטיוטה נשמרה ✓',

  // drip content
  dripDaysLabel: 'שחרור מדורג (ימים)',
  dripHint: 'הפרק ייפתח רק כעבור מספר הימים הזה מרגע ההרשמה (0 = נפתח מיד)',
  dripLockedIn: 'נפתח בעוד {n} ימים',
  moduleLockedTitle: 'הפרק עוד לא נפתח',

  // social channels (shown on landing pages + LinkTree)
  socialWhatsapp: 'וואטסאפ',
  socialInstagram: 'אינסטגרם',
  socialFacebook: 'פייסבוק',
  socialTiktok: 'טיקטוק',
  socialYoutube: 'יוטיוב',
  socialLinkedin: 'לינקדאין',
  socialWebsite: 'אתר הבית',
  socialEmail: 'אימייל',
  landingFollowUs: 'עוקבים אחרינו',

  // admin — links & socials page
  linksTitle: 'קישורים ורשתות',
  linksSubtitle: 'הרשתות החברתיות של בית הספר ועמוד קישורים אחד לביו — הכול במקום אחד.',
  adminItemLinksDesc: 'רשתות חברתיות, מספר וואטסאפ ועמוד LinkTree ממותג לביו.',
  socialsCardTitle: 'רשתות חברתיות',
  socialsCardSubtitle: 'מה שתמלאו כאן יופיע בתחתית כל דפי המכירה ובעמוד הקישורים.',
  socialsWhatsappHint: 'מספר בפורמט ישראלי (050…) או בינלאומי — נהפוך אותו לקישור wa.me',
  socialsUrlPlaceholder: 'https://…',
  linktreeCardTitle: 'עמוד הקישורים (LinkTree)',
  linktreeCardSubtitle:
    'עמוד ציבורי ממותג עם כל הקישורים שלכם — שמים אותו בביו של אינסטגרם/טיקטוק וכל הדרכים מובילות אליכם.',
  linktreeLogo: 'הלוגו של העסק',
  linktreeLogoHint: 'מופיע בראש עמוד הקישורים. זה אותו לוגו כמו במיתוג בית הספר — עדכון כאן מתעדכן בכל מקום.',
  linktreePublish: 'עמוד פעיל',
  linktreePublishHint: 'כשהעמוד כבוי הוא זמין רק לכם כתצוגה מקדימה.',
  linktreeHeadline: 'כותרת',
  linktreeHeadlinePlaceholder: 'ריק = שם בית הספר',
  linktreeBio: 'משפט עליכם',
  linktreeBioPlaceholder: 'מי אתם ומה מקבלים אצלכם — משפט או שניים',
  linktreeTheme: 'ערכת צבע',
  linktreeButtonStyle: 'סגנון כפתורים',
  linktreeButtonSolid: 'מלא',
  linktreeButtonOutline: 'קו מתאר',
  linktreeButtonSoft: 'רך',
  linktreeLinksTitle: 'הקישורים',
  linktreeLinksHint: 'כל קישור שתרצו — קורסים, יוטיוב, קבוצת וואטסאפ, טופס הרשמה. גררו בחצים לשינוי סדר.',
  linktreeAddLink: 'הוספת קישור',
  linktreeLinkLabel: 'טקסט הכפתור',
  linktreeLinkUrl: 'כתובת (URL)',
  linktreeLinkEmoji: 'אימוג׳י',
  linktreeNoLinks: 'עוד אין קישורים — הוסיפו את הראשון.',
  linktreeYourUrl: 'הכתובת הציבורית שלכם',
  linktreeCopyUrl: 'העתקת קישור',
  linktreeCopied: 'הועתק ✓',
  linktreeOpenPreview: 'תצוגה מקדימה',
  linktreeMoveUp: 'הזזה למעלה',
  linktreeMoveDown: 'הזזה למטה',
  linktreeRemoveLink: 'הסרה',
  linktreeSaved: 'נשמר ✓',
  linktreePreviewBanner: 'תצוגה מקדימה — העמוד עוד לא פורסם. רק אתם רואים אותו.',

  // course-taking workspace (student lesson view)
  learnCourseContent: 'תוכן הקורס',
  learnYourProgress: 'ההתקדמות שלכם',
  learnProgressOf: '{done} מתוך {n} הושלמו',
  learnTabOverview: 'סקירה',
  learnTabAnnouncements: 'הודעות',
  learnTabCourseContent: 'תוכן הקורס',
  learnSection: 'פרק {i}: {title}',
  learnSectionMeta: '{done} / {n} · {min} דק׳',
  learnLectureMin: '{min} דק׳',
  learnMarkComplete: 'סימון השיעור כהושלם',
  learnLectureDone: 'השיעור הושלם',
  learnAboutLesson: 'על השיעור הזה',
  learnNoDescription: 'המדריך/ה עוד לא הוסיפ/ה תיאור לשיעור הזה',
  learnResources: 'חומרים לשיעור',
  learnNoAnnouncements: 'אין הודעות חדשות מבית הספר',
  learnHideSidebar: 'הסתרת תוכן הקורס',
  learnShowSidebar: 'הצגת תוכן הקורס',
  learnBackHome: 'הקורסים שלי',
  learnAutoNext: 'השיעור הבא מתחיל...',
  learnCourseEmpty: 'הקורס הזה עוד לא כולל שיעורים',
  learnLectureOf: 'שיעור {i} מתוך {n}',
  learnShareEarn: 'שיתוף והטבות',
  learnLeaveRating: 'דירוג הקורס',

  // "my learning" home
  myLearningTitle: 'הלמידה שלי',
  myLearningAll: 'כל הקורסים',
  myLearningInProgress: 'בתהליך',
  myLearningDone: 'הושלמו',
  myLearningPct: '{pct}% הושלמו',
  myLearningStart: 'התחלת הקורס',
  myLearningBy: 'מאת',
} as const;

export type HeKey = keyof typeof he;
