export const he = {
  appName: 'קורסים',
  admin: 'ניהול',
  superAdmin: 'ניהול מערכת',
  platformTagline: 'פלטפורמת הקורסים לעסקים שמוכרים ידע',

  // auth
  login: 'התחברות',
  logout: 'התנתקות',
  email: 'אימייל',
  password: 'סיסמה',
  currentPassword: 'סיסמה נוכחית',
  newPassword: 'סיסמה חדשה',
  changePassword: 'החלפת סיסמה',
  mustChangePassword: 'רגע לפני שממשיכים — צריך לבחור סיסמה חדשה',
  invalidCredentials: 'אימייל או סיסמה שגויים',
  accountSuspended: 'החשבון מושעה',
  tooManyAttempts: 'יותר מדי ניסיונות. שנייה של אוויר, ומנסים שוב',
  deviceLimitReached: 'חריגה ממגבלת המכשירים',
  deviceLimitExplain: 'החשבון כבר מחובר במספר המכשירים המרבי. מתנתקים מאחד מהם וממשיכים.',
  activeDevices: 'מכשירים מחוברים',
  evictedNotice: 'החשבון הופעל ממכשיר אחר',
  loggingIn: 'מתחברים...',
  loginWelcome: 'טוב שחזרתם',
  loginSubtitle: 'מתחברים וממשיכים בדיוק מאיפה שעצרתם.',
  authPanelTitle: 'החשבון שלכם, המכשירים שלכם. לא של אף אחד אחר.',
  authPanelText: 'כל חשבון מוגן במגבלת מכשירים חכמה — כך שהתוכן שרכשתם נשאר שלכם בלבד.',
  deviceLimitTitle: 'הגעתם למגבלת המכשירים',
  deviceLimitBody: 'החשבון כבר מחובר במספר המכשירים המרבי. כדי להיכנס מכאן, מתנתקים מאחד המכשירים שלמטה ומנסים שוב. אין לחץ — זה קורה לכולם 🙂',
  devicesInUse: 'מכשירים בשימוש',
  outOf: 'מתוך',
  retryAfterLogout: 'ניתקתי — לנסות שוב',
  backToLogin: 'חזרה להתחברות',
  dontRecognizeHint: 'לא מזהים אחד מהמכשירים? מומלץ להחליף סיסמה מיד עם הכניסה.',
  evictedBody: 'מישהו נכנס לחשבון ממכשיר חדש, ולכן המכשיר הזה נותק אוטומטית. אם זה הייתם אתם — פשוט מתחברים מחדש.',
  passwordHint: 'לפחות 8 תווים',

  // nav
  dashboard: 'לוח בקרה',
  courses: 'קורסים',
  students: 'תלמידים',
  sessions: 'חיבורים פעילים',
  settings: 'הגדרות',
  backToCourses: 'חזרה לקורסים',
  myCourses: 'הקורסים שלי',
  navMain: 'ראשי',
  logoAria: 'לוגו קורסים',

  // common
  save: 'שמירה',
  cancel: 'ביטול',
  delete: 'מחיקה',
  create: 'יצירה',
  add: 'הוספה',
  edit: 'עריכה',
  close: 'סגירה',
  copy: 'העתקה',
  copied: 'הועתק!',
  loading: 'טוען...',
  none: 'אין',
  optional: '(לא חובה)',
  unsavedChanges: 'יש שינויים שעוד לא נשמרו',
  noStudentsYet: 'עוד אין תלמידים',
  noEnrollmentsYet: 'עוד אין רישומים',
  noTenantsYet: 'עוד אין בתי ספר',
  noAffiliatesYet: 'עוד אין שגרירים',
  confirmDelete: 'למחוק? אי אפשר לבטל את הפעולה.',
  error: 'שגיאה',
  saved: 'נשמר',

  // courses
  courseTitle: 'שם הקורס',
  courseDescription: 'תיאור',
  newCourse: 'קורס חדש',
  draft: 'טיוטה',
  published: 'מפורסם',
  publish: 'פרסום',
  unpublish: 'החזרה לטיוטה',
  modules: 'פרקים',
  newModule: 'פרק חדש',
  moduleTitle: 'שם הפרק',
  lessons: 'שיעורים',
  newLesson: 'שיעור חדש',
  lessonTitle: 'שם השיעור',
  lessonNotes: 'הערות לשיעור',
  noCourses: 'עוד אין קורסים',
  noLessons: 'אין שיעורים בפרק הזה',
  modulesEmptyHint: 'מתחילים בפרק ראשון — ואז מוסיפים אליו שיעורים',
  enrollments: 'רישומים',
  enrollStudent: 'רישום תלמיד לקורס',
  unenroll: 'הסרת רישום',
  lessonCount: 'שיעורים',
  enrollmentsEmptyHint: 'תלמידים שיירשמו לקורס יופיעו כאן',
  courseTitlePlaceholder: 'למשל: שיווק דיגיטלי למתחילים',
  courseTitleHint: 'יוצג לתלמידים בתוך המערכת',

  // media
  video: 'וידאו',
  uploadVideo: 'העלאת וידאו',
  replaceVideo: 'החלפת וידאו',
  removeVideo: 'הסרת וידאו',
  uploading: 'מעלה...',
  uploadFailed: 'ההעלאה נכשלה',
  attachments: 'קבצים מצורפים',
  addAttachment: 'צירוף קובץ',
  noVideo: 'עוד לא הועלה וידאו לשיעור הזה',
  cloudinaryMissing: 'Cloudinary לא מוגדר — הגדירו מפתחות ב-.env כדי להעלות מדיה',
  download: 'הורדה',

  // students
  newStudent: 'תלמיד חדש',
  role: 'תפקיד',
  student: 'תלמיד',
  instructor: 'מדריך',
  owner: 'בעלים',
  status: 'סטטוס',
  active: 'פעיל',
  suspended: 'מושעה',
  suspend: 'השעיה',
  activate: 'הפעלה',
  resetPassword: 'איפוס סיסמה',
  lastLogin: 'התחברות אחרונה',
  liveSessions: 'חיבורים חיים',
  viewSessions: 'צפייה בחיבורים',
  killSession: 'ניתוק',
  emailTaken: 'האימייל כבר רשום',
  enrolledCourses: 'קורסים רשומים',
  studentsEmptyHint: 'הוסיפו תלמיד ראשון או שלחו קישור הזמנה',
  newStudentPasswordHint: 'התלמיד יתבקש להחליף סיסמה בכניסה הראשונה',
  studentsSubtitle: 'ניהול חשבונות, הזמנות וחיבורים של התלמידים',
  deviceUnknown: 'מכשיר לא מזוהה',

  // invites
  invites: 'הזמנות',
  newInvite: 'הזמנה חדשה',
  inviteLink: 'קישור הזמנה',
  inviteLinkNote: 'הקישור מוצג פעם אחת בלבד — העתיקו ושלחו לתלמיד עכשיו',
  inviteExpires: 'תוקף',
  inviteUsed: 'נוצל',
  inviteFor: 'מיועד ל',
  anyEmail: 'כל אימייל',
  acceptInviteTitle: 'רגע אחד — והחשבון שלכם מוכן',
  invalidInvite: 'קישור ההזמנה אינו תקף או שפג תוקפו',
  createAccount: 'יצירת החשבון שלי',
  accountCreated: 'החשבון מוכן! אפשר להתחבר ולהתחיל',
  inviteePanelTitle: 'הוזמנתם ללמוד איתנו',
  inviteePanelText: 'דקה של הרשמה — וכל הקורסים, השיעורים והחומרים מחכים לכם.',

  // sessions
  device: 'מכשיר',
  ipAddress: 'כתובת IP',
  connectedSince: 'מחובר מאז',
  lastSeen: 'נראה לאחרונה',
  whoIsWatching: 'מי מחובר עכשיו',
  noLiveSessions: 'אין חיבורים פעילים כרגע',
  noLiveSessionsHint: 'ברגע שתלמידים ייכנסו לצפות, הם יופיעו כאן בזמן אמת.',
  liveUpdate: 'עדכון חי',
  sessionsSummary: '{n} חיבורים פעילים אצל {m} תלמידים',
  policyPrefix: 'המדיניות:',
  upToDevices: 'עד {n} מכשירים לתלמיד/ה',
  searchByEmail: 'חיפוש לפי אימייל…',
  atLimitBadge: 'במגבלה',
  multiIpWarning: 'כמה כתובות IP שונות בו־זמנית — ייתכן שהחשבון משותף. שווה לבדוק.',
  refreshedPrefix: 'עודכן',

  // settings
  tenantName: 'שם בית הספר',
  sessionLimit: 'מגבלת מכשירים לתלמיד',
  sessionLimitSubtitle: 'כמה מכשירים יכולים להיות מחוברים בו-זמנית לאותו חשבון',
  evictionPolicy: 'מה קורה בחריגה מהמגבלה',
  policyBlock: 'חסימת התחברות חדשה',
  policyBlockHint: 'מכשיר נוסף מעבר למגבלה לא יצליח להתחבר עד שמכשיר קיים יתנתק',
  policyEvictOldest: 'ניתוק המכשיר הישן ביותר',
  policyEvictOldestHint: 'התחברות חדשה תנתק אוטומטית את המכשיר הכי פחות פעיל',

  // player
  progress: 'התקדמות',
  completed: 'הושלם',
  continueWatching: 'המשך צפייה',

  // marketing & landing pages
  marketing: 'שיווק ודף נחיתה',
  landingPage: 'דף נחיתה',
  landingPreview: 'תצוגה מקדימה',
  landingPublish: 'פרסום הדף',
  landingUnpublish: 'הסרה מפרסום',
  landingPublished: 'הדף פומבי',
  landingDraftBadge: 'עדיין לא פורסם',
  landingLink: 'קישור לדף הנחיתה',
  landingShareNote: 'שתפו את הקישור בכל מקום — הדף פתוח לכולם, בלי צורך בהתחברות',
  aiMediaTitle: 'סרטון שיווקי ב-AI',
  aiMediaHint: 'צרו סרטון קולנועי מותאם לקורס — הוא יופיע כאנימציית גלילה מרהיבה בראש דף הנחיתה',
  aiMediaGenerate: 'ליצירת סרטון עם AI',
  aiMediaRegenerate: 'ליצירה מחדש',
  aiMediaGenerating: 'יוצרים לכם סרטון מותאם אישית… זה יכול לקחת כמה דקות',
  aiMediaReady: 'הסרטון מוכן ומופיע בדף הנחיתה',
  aiMediaFailed: 'יצירת הסרטון נכשלה. נסו שוב',
  aiMediaDisabled: 'יצירת מדיה ב-AI אינה מופעלת בשרת',
  aiMediaCloudinaryMissing: 'צריך להגדיר Cloudinary כדי לשמור את הסרטון',
  headline: 'כותרת ראשית',
  headlineSubtitle: 'הכותרת שמקבלת את הפנים בדף הנחיתה',
  headlineHint: 'הכותרת הגדולה בדף הנחיתה — אם ריק, נשתמש בשם הקורס',
  subheadline: 'משפט משנה',
  subheadlinePlaceholder: 'משפט אחד שגורם למבקר להבין למה הקורס הזה בשבילו',
  aboutSchool: 'על בית הספר / המדריך',
  aboutSchoolPlaceholder: 'כמה מילים עליכם — ניסיון, גישה, ולמה כדאי ללמוד דווקא אצלכם',
  instructorName: 'שם המדריך',
  withInstructor: 'עם',
  audienceTitle: 'למי הקורס הזה מתאים',
  audienceItem: 'קהל יעד (למשל: יזמים בתחילת הדרך)',
  outcomesTitle: 'מה תדעו לעשות בסוף הקורס',
  outcomeItem: 'תוצאה (למשל: לבנות תקציב חודשי שמחזיק)',
  benefitsTitle: 'למה דווקא אצלנו',
  benefitTitle: 'כותרת יתרון',
  benefitBody: 'פירוט קצר',
  testimonialsTitle: 'מה אומרים הבוגרים',
  testimonialName: 'שם הממליץ',
  testimonialQuote: 'ציטוט ההמלצה',
  faqTitle: 'שאלות נפוצות',
  faqQ: 'שאלה',
  faqA: 'תשובה',
  priceText: 'מחיר (טקסט חופשי, למשל: 490 ₪)',
  ctaText: 'טקסט כפתור ההרשמה',
  ctaLink: 'קישור הרשמה (וואטסאפ / טופס / סליקה)',
  ctaLinkSubtitle: 'לאן מגיעים בלחיצה על כפתור ההרשמה',
  ctaLinkHint: 'קישור חלופי כשאין דף תשלום — וואטסאפ או טופס הרשמה',
  contactPhone: 'טלפון ליצירת קשר',
  contactEmail: 'אימייל ליצירת קשר',
  accentTitle: 'צבע הדף',
  emojiTitle: 'אייקון הקורס',
  curriculum: 'מה לומדים בקורס',
  enrollNow: 'רוצה להתחיל',
  digitalCourseBadge: 'קורס דיגיטלי',
  hoursVideo: 'שעות וידאו',
  yourInstructor: 'המנחה שלכם',
  ctaCoinsNote: '🪙 משתפים את הקורס אחרי הרכישה — וצוברים מטבעות',
  ctaAccessNote: 'גישה מיידית לכל השיעורים, לכל החיים. צופים מכל מכשיר — עד {n} במקביל.',
  paymentLink: 'קישור לתשלום (דף סליקה)',
  paymentLinkHint: 'כשמגדירים קישור — כפתור ההרשמה בדף הנחיתה יוביל ישירות לתשלום',
  payNow: 'מעבר לתשלום מאובטח',
  galleryTitle: 'הצצה מבפנים',
  gallerySection: 'גלריה — תמונות וסרטונים קצרים',
  addPhoto: 'הוספת תמונה',
  addVideo: 'הוספת סרטון',
  galleryCaption: 'כיתוב (לא חובה)',
  galleryHint: 'עד 8 פריטים. תמונות, סרטונים קצרים ותוצאות לפני/אחרי',
  galleryAfterCreate: 'אפשר להעלות גלריה אחרי יצירת הקורס, בלשונית השיווק',
  addBeforeAfter: 'הוספת לפני/אחרי',
  beforeLabel: 'לפני',
  afterLabel: 'אחרי',
  beforeAfterHint: 'בוחרים קודם את תמונת ה"לפני", ומיד אחריה את תמונת ה"אחרי"',
  galleryBeforeDone: '✓ תמונת ה"לפני" הועלתה — עכשיו בחרו את תמונת ה"אחרי"',
  galleryPickAfter: 'בחירת תמונת ה"אחרי"',

  // landing sale / bundle offer
  saleSection: 'מבצע בדף הנחיתה',
  saleSectionHint: 'חברו קורס נוסף והציעו הטבה — למשל 1+1 או הנחה על הקורס השני',
  saleEnable: 'הצגת המבצע בדף הנחיתה',
  saleTitleLabel: 'כותרת המבצע',
  saleTitlePlaceholder: 'למשל: קונים קורס אחד — מקבלים את השני מתנה!',
  saleDescriptionLabel: 'פרטי המבצע (טקסט חופשי)',
  salePartnerCourse: 'הקורס שמצטרף למבצע',
  salePartnerNone: 'ללא קורס מקושר',
  salePaymentLink: 'קישור לתשלום עבור המבצע',
  salePaymentLinkHint: 'דף סליקה ייעודי לעסקת המבצע — כפתור המבצע בדף הנחיתה יוביל אליו',
  saleEndsAt: 'בתוקף עד (לא חובה)',
  saleEndsAtHint: 'אחרי התאריך הזה המבצע ייעלם מדף הנחיתה אוטומטית',
  saleBadge: 'מבצע מיוחד',
  saleEndsOn: 'המבצע בתוקף עד',
  saleCta: 'לתפוס את המבצע',
  saleIncludedCourse: 'הקורס שמצטרף למבצע',
  saleExpired: 'תאריך המבצע עבר — הוא מוסתר מדף הנחיתה',
  saleEndsIn: 'המבצע נגמר בעוד',
  countdownDays: 'ימים',
  countdownHours: 'שעות',
  countdownMinutes: 'דקות',
  countdownSeconds: 'שניות',

  // landing conversion / trust
  trustInstantAccess: 'גישה מיידית',
  trustLifetime: 'לכל החיים',
  trustAnyDevice: 'צפייה מכל מכשיר',
  trustSecurePayment: 'תשלום מאובטח',
  studentsEnrolled: 'תלמידים כבר לומדים כאן',
  midCtaTitle: 'אז מתחילים?',
  midCtaSubtitle: 'נרשמים עכשיו ומקבלים גישה מיידית לכל השיעורים — לכל החיים',
  limitedOffer: 'ההרשמה פתוחה עכשיו',

  // student reviews
  reviews: 'ביקורות תלמידים',
  reviewsTitle: 'מה אומרים תלמידים אמיתיים',
  writeReview: 'איך היה הקורס?',
  writeReviewHint: 'סיימתם את הקורס — נשמח לשמוע! הביקורת תופיע בדף הקורס אחרי אישור',
  reviewRating: 'דירוג',
  reviewText: 'הביקורת שלכם',
  reviewSubmit: 'שליחת הביקורת',
  reviewThanks: 'תודה רבה! הביקורת נשלחה ותופיע אחרי אישור',
  reviewApprove: 'אישור והצגה',
  reviewHide: 'הסתרה',
  reviewPending: 'ממתינה לאישור',
  reviewApproved: 'מוצגת בדף',
  noReviews: 'עוד אין ביקורות',
  reviewsEmptyHint: 'תלמידים שיסיימו את הקורס יתבקשו להשאיר ביקורת — היא תופיע כאן לאישור',
  verifiedStudent: 'תלמיד/ה מאומת/ת',
  reviewPrivateNote: 'הערה למדריך (לא תפורסם)',
  reviewPrivateNoteHint: 'משוב אישי, בקשות או הצעות — יגיעו רק למנהל הקורס',
  reviewEdit: 'עריכת הביקורת',
  reviewEditNote: 'אפשר ללטש את הניסוח לפני הפרסום — הגרסה הערוכה תופיע בדף הנחיתה',
  privateNoteBadge: 'הערה פרטית',

  // course catalog (buy more courses)
  moreCourses: 'עוד קורסים בבית הספר',
  moreCoursesHint: 'קורסים שאפשר להצטרף אליהם כבר עכשיו',
  viewCourse: 'לפרטים והרשמה',

  // affiliates
  affiliateTitle: 'שתפו את הקורס וצברו מטבעות 🪙',
  affiliateHint: 'שתפו את הקישור האישי שלכם — כל {n} מבקרים חדשים בדף הקורס מזכים אתכם במטבע',
  affiliateYourLink: 'הקישור האישי שלכם',
  affiliateVisits: 'מבקרים ייחודיים',
  affiliateCoins: 'מטבעות שצברתם',
  affiliateToNext: 'עוד {n} מבקרים למטבע הבא',
  affiliateGetLink: 'קבלת קישור לשיתוף',
  shareWhatsapp: 'שיתוף בוואטסאפ',
  shareInstagram: 'שיתוף בסטורי',
  shareGeneric: 'שיתוף...',
  shareText: 'שווה לכם להציץ בקורס שאני לומד/ת:',
  instagramCopied: 'הקישור הועתק! פתחו סטורי באינסטגרם והוסיפו אותו כסטיקר קישור (Link)',
  affiliatesSection: 'שיווק שותפים',
  affiliatesEmpty: 'עוד אין שותפים — תלמידים שרכשו את הקורס יכולים לשתף קישור אישי ולצבור מטבעות',

  // course completion summary
  courseCompletedTitle: 'כל הכבוד, סיימתם את הקורס! 🎓',
  courseCompletedSub: 'הנה סיכום קצר של הדרך שעברתם',
  whatWeLearned: 'מה למדנו בקורס',
  summaryLessons: 'שיעורים',
  addItem: 'הוספת פריט',
  removeItem: 'הסרה',

  // onboarding wizard
  newCourseWizard: 'קורס חדש',
  wizardKicker: 'אשף הקמת קורס',
  wizardIntro: 'כמה שאלות קצרות — ובסוף מחכה לכם גם דף נחיתה מוכן לשיווק',
  wizardStepsAria: 'שלבים',
  stepBasics: 'פרטי הקורס',
  stepAudience: 'קהל ותוצאות',
  stepBenefits: 'יתרונות',
  stepSocial: 'הוכחה חברתית',
  stepPricing: 'מחיר והרשמה',
  stepStyle: 'עיצוב הדף',
  next: 'הבא',
  back: 'חזרה',
  skip: 'דילוג',
  finish: 'סיום ויצירה',
  optionalStep: 'אפשר לדלג ולהשלים אחר כך',
  wizardDone: 'הקורס נוצר!',
  wizardDoneHint: 'עכשיו אפשר לערוך תוכן, להוסיף שיעורים ולפרסם את דף הנחיתה',
  goToCourse: 'לעריכת הקורס',

  // student home dashboard
  greetingMorning: 'בוקר טוב',
  greetingNoon: 'צהריים טובים',
  greetingEvening: 'ערב טוב',
  greetingNight: 'לילה טוב',
  homeSubtitle: 'ממשיכים מאיפה שעצרתם — ההתקדמות נשמרת אוטומטית',
  noCoursesHint: 'ברגע שתירשמו לקורס — הוא יופיע כאן',
  continueLearning: 'ממשיכים ללמוד',
  nextLessonLabel: 'השיעור הבא',
  allCaughtUp: 'כל הכבוד! סיימתם הכול 🎉',
  allCaughtUpHint: 'אולי זה הזמן להרפתקה חדשה? הציצו בקטלוג הקורסים',
  streakDays: 'ימי רצף',
  statsStreak: 'רצף נוכחי',
  statsLessonsDone: 'שיעורים שהושלמו',
  statsCoursesDone: 'קורסים שהושלמו',
  statsMinutes: 'דקות למידה',
  announcementsTitle: 'לוח מודעות',
  aboutSchoolTitle: 'על בית הספר',
  featuredCourse: 'קורס מומלץ',

  // journey page
  journeyTitle: 'המסע שלי',
  journeySubtitle: 'ההתקדמות, הרצף וההישגים שלכם — הכול במקום אחד',
  activityLast4Weeks: 'פעילות בארבעת השבועות האחרונים',
  activityDaysCount: 'ימי למידה בחודש האחרון',
  perCourseProgress: 'התקדמות לפי קורס',
  achievementsTitle: 'הישגים',
  achievementLocked: 'עוד לא נפתח',
  viewAllAchievements: 'לכל ההישגים',
  achievementsUnlocked: 'הישגים שנפתחו',
  achFirstLesson: 'צעד ראשון',
  achFirstLessonDesc: 'סיימתם את השיעור הראשון',
  achLessons5: 'תופסים תאוצה',
  achLessons5Desc: '5 שיעורים הושלמו',
  achLessons10: 'ממריאים',
  achLessons10Desc: '10 שיעורים הושלמו',
  achLessons25: 'כובשים פסגות',
  achLessons25Desc: '25 שיעורים הושלמו',
  achFirstCourse: 'קו הסיום',
  achFirstCourseDesc: 'קורס ראשון הושלם במלואו',
  achCourses3: 'אספני ידע',
  achCourses3Desc: '3 קורסים הושלמו',
  achStreak3: 'על הגל',
  achStreak3Desc: '3 ימי למידה ברצף',
  achStreak7: 'שבוע מושלם',
  achStreak7Desc: '7 ימי למידה ברצף',

  // owner homepage builder
  homepageBuilder: 'עמוד הבית',
  homepageBuilderSubtitle: 'כך ייראה עמוד הבית של התלמידים — עיצוב, הודעות ותוכן על בית הספר',
  homepageWelcome: 'ברכת פתיחה',
  homepageWelcomeHeadline: 'כותרת פתיחה (מוצגת ליד הברכה)',
  homepageWelcomeHeadlinePlaceholder: 'למשל: ברוכים הבאים לסטודיו!',
  homepageAboutSchool: 'על בית הספר',
  homepageAboutSchoolHint: 'כמה משפטים על בית הספר — יוצגו לתלמידים בעמוד הבית',
  homepageAnnouncements: 'הודעות ועדכונים',
  homepageAnnouncementsHint: 'עד 10 הודעות — החדשות למעלה. יוצגו בלוח המודעות של התלמידים',
  announcementTitle: 'כותרת ההודעה',
  announcementBody: 'תוכן ההודעה',
  announcementDate: 'תאריך',
  homepageSections: 'אילו אזורים להציג',
  homepageShowStats: 'שורת נתונים אישיים (שיעורים, רצף, דקות)',
  homepageShowAchievements: 'הישגים',
  homepageShowCatalog: 'קטלוג קורסים נוספים',
  homepageFeaturedCourse: 'קורס מודגש בקטלוג',
  homepageFeaturedNone: 'ללא',
  homepagePreview: 'תצוגה מקדימה',
  homepageStyle: 'עיצוב עמוד הבית',

  // superadmin
  tenants: 'בתי ספר',
  newTenant: 'בית ספר חדש',
  tenantSlug: 'מזהה (slug)',
  tenantSlugHint: 'אותיות לועזיות קטנות ומקפים בלבד — יופיע בכתובת',
  ownerEmail: 'אימייל הבעלים',
  ownerPassword: 'סיסמת הבעלים',
  ownerPasswordHint: 'הבעלים יתבקש להחליף סיסמה בכניסה הראשונה',
  usersCount: 'משתמשים',
  coursesCount: 'קורסים',
  slugTaken: 'המזהה כבר תפוס',
  openTenant: 'מעבר לבית הספר',
  tenantsEmptyHint: 'צרו את בית הספר הראשון בפלטפורמה',
  tenantsSubtitle: 'כל בתי הספר בפלטפורמה — יצירה, השעיה ומחיקה',
  superAdminLoginSubtitle: 'כניסה למנהלי הפלטפורמה בלבד',
  superAdminPanelTitle: 'שליטה מלאה בפלטפורמה',
  superAdminPanelText: 'ניהול בתי ספר, השעיות ומעקב שימוש — מכל מקום, בבטחה.',

  // owner admin dashboard
  adminOverviewTitle: 'מה קורה בבית הספר',
  adminSessionsEmptyHint: 'חיבורים חיים יופיעו כאן ברגע שתלמידים ייכנסו',

  // platform marketing homepage (/)
  platformHeroTitle1: 'בית ספר דיגיטלי משלכם,',
  platformHeroTitle2: 'בלי שהסיסמה תעבור מיד ליד',
  platformHeroText: 'מעלים שיעורי וידאו, מנהלים תלמידים ובונים דפי נחיתה שמוכרים — עם הגבלת מכשירים חכמה ששומרת שהתוכן שיצרתם יישאר שלכם.',
  platformCtaAdmin: 'כניסת מנהל המערכת',
  platformTenantHint: 'תלמידים ובעלי קורסים נכנסים דרך הכתובת של בית הספר שלהם: ‎/t/שם-בית-הספר',
  platformDemoConnections: '3 חיבורים',
  platformDemoNow: 'עכשיו',
  platformDemoAgoMin: 'לפני דקה',
  platformDemoAgo4Min: 'לפני 4 דקות',
  platformDemoBlocked: 'מכשיר רביעי נחסם — חריגה ממגבלת המכשירים',
  platformFooterTagline: 'נבנה לבתי ספר דיגיטליים',

  // page metadata
  metaTitle: 'Kursim — פלטפורמת קורסים',
  metaDescription: 'פלטפורמה רב-ארגונית לבתי ספר דיגיטליים, עם הגבלת מכשירים חכמה ששומרת על התוכן שלכם',

  // landing footer
  landingBuiltWith: 'נבנה עם Kursim',
} as const;

export type HeKey = keyof typeof he;
